'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { api, ApiError, MyWorkItem, MyWorkResponse } from '../../lib/api-client';
import {clearReadCache,readCache,writeCache} from '../../lib/read-cache';
import {MyWorkFilter,toggleFilter} from '../../lib/operational-filters';
import {Pagination} from '../../components/pagination';
import styles from './my-work.module.css';

export default function MyWorkPage(){
  const [data,setData]=useState<MyWorkResponse|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState<MyWorkFilter>('open'),[search,setSearch]=useState(''),[page,setPage]=useState(1);
  const load=useCallback(async()=>{const key=`my-work:${page}:${filter}:${search.trim().toLowerCase()}`,cached=readCache<MyWorkResponse>(key);if(cached){setData(cached);setLoading(false)}else setLoading(true);setError('');try{const response=await api.getMyWork(page,50,{filter,search});if(page>1&&!response.items.length&&response.total>0){setPage(Math.max(1,Math.ceil(response.total/response.pageSize)));return}setData(response);writeCache(key,response)}catch(cause){const auth=cause instanceof ApiError&&['UNAUTHENTICATED','SESSION_EXPIRED','FORBIDDEN'].includes(cause.code);if(!cached||auth){if(auth){clearReadCache();setData(null)}setError(cause instanceof ApiError?cause.message:'Your work queue could not be loaded.')}}finally{setLoading(false)}},[page,filter,search]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),search?250:0);return()=>window.clearTimeout(timer)},[load,search]);
  const items=data?.items||[],summary=data?.summary||{open:0,overdue:0,dueToday:0,high:0},cards:Array<[string,number,MyWorkFilter]>=[['Open Work',summary.open,'open'],['Overdue',summary.overdue,'overdue'],['Due Today',summary.dueToday,'today'],['High Priority',summary.high,'high']];
  return <><div className="section-head"><div><h1>My Work</h1><p className="muted">Your live assigned queue, ordered by urgency and due time.</p></div>{!loading&&<button className={styles.refresh} onClick={()=>void load()}>Refresh</button>}</div>
    <div className={styles.summary}>{cards.map(([label,value,key])=><button type="button" aria-pressed={filter===key} className={`card ${styles.summaryButton} ${filter===key?styles.summaryActive:''}`} key={key} onClick={()=>{setPage(1);setFilter(current=>toggleFilter(current,key,'open'))}}><span>{label}</span><b>{value}</b></button>)}</div>
    <div className={styles.search}><input value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}} placeholder="Search username, name, email, phone or brand" aria-label="Search My Work"/>{data&&<p>{data.total} matching work item{data.total===1?'':'s'}</p>}</div>
    {loading&&!data?<QueueState title="Loading your queue…" detail="Retrieving current assignments and prospect details."/>:error?<QueueState title="Unable to load My Work" detail={error} action={<button className="primary" onClick={()=>void load()}>Retry</button>}/>:!summary.open?<QueueState title="You’re all caught up" detail="No active assigned work items are waiting for you."/>:!items.length?<QueueState title="No matching work" detail={`No work matches this filter or search. ${summary.open} open item${summary.open===1?' exists':'s exist'} in your queue.`}/>:<><Queue items={items}/><Pagination page={data!.page} pageSize={data!.pageSize} total={data!.total} onPageChange={setPage}/></>}</>;
}
function Queue({items}:{items:MyWorkItem[]}){return <section className="card"><div className="section-head"><div><h2>Active queue</h2><p className="muted">{items.length} open item{items.length===1?'':'s'}</p></div></div><div className={styles.tableWrap}><table className="table"><thead><tr><th>Affiliate</th><th>Brand</th><th>Work</th><th>Channel</th><th>Priority</th><th>Status</th><th>Due</th><th>Contact</th><th>Action</th></tr></thead><tbody>{items.map(item=><tr className={item.overdue?styles.overdueRow:''} key={item.workId}><td><strong>{item.affiliateUsername||'Unknown'}</strong><small>{item.affiliateName||'Name not provided'}</small></td><td>{item.brandName||item.brandCode||item.brandId||'—'}</td><td>{label_(item.workType)}</td><td>{label_(item.workChannel)}</td><td><Badge value={item.priority}/></td><td><Badge value={item.overdue?'OVERDUE':item.status}/></td><td>{due_(item.dueAt)}</td><td><small>{item.email||'No email'}</small><small>{item.phone||'No phone'}</small></td><td><Link className={styles.open} href={`/affiliates?workId=${encodeURIComponent(item.workId)}`}>Open</Link></td></tr>)}</tbody></table></div><div className={styles.mobileList}>{items.map(item=><article className={styles.mobileCard} key={item.workId}><div><strong>{item.affiliateUsername||'Unknown'}</strong><span>{item.affiliateName||'Name not provided'}</span></div><div className={styles.badges}><Badge value={item.priority}/><Badge value={item.overdue?'OVERDUE':item.status}/></div><dl><div><dt>Brand</dt><dd>{item.brandName||item.brandCode||item.brandId||'—'}</dd></div><div><dt>Work</dt><dd>{label_(item.workType)} · {label_(item.workChannel)}</dd></div><div><dt>Due</dt><dd>{due_(item.dueAt)}</dd></div><div><dt>Contact</dt><dd>{item.email||item.phone||'Not provided'}</dd></div></dl><Link className={styles.open} href={`/affiliates?workId=${encodeURIComponent(item.workId)}`}>Open</Link></article>)}</div></section>}
function QueueState({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}){return <section className="card empty-state"><div><div className="empty-icon">✓</div><h2>{title}</h2><p className="muted">{detail}</p>{action}</div></section>}
function Badge({value}:{value:string}){const key=String(value||'').toUpperCase();return <span className={`${styles.badge} ${key==='OVERDUE'||key==='HIGH'?styles.urgent:''}`}>{label_(key)}</span>}
function label_(value:string){return String(value||'—').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function due_(value:string){if(!value)return'No due date';const date=new Date(value);if(Number.isNaN(date.getTime()))return'Invalid date';return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(date)}
