'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { api, ApiError, MyWorkItem } from '../../lib/api-client';
import styles from './my-work.module.css';

export default function MyWorkPage(){
  const [items,setItems]=useState<MyWorkItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await api.getMyWork();setItems(response.items)}catch(cause){setError(cause instanceof ApiError?cause.message:'Your work queue could not be loaded.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
  const summary=useMemo(()=>{const current=new Date();return {open:items.length,overdue:items.filter(x=>x.overdue).length,dueToday:items.filter(x=>isToday_(x.dueAt,current)).length,high:items.filter(x=>String(x.priority).toUpperCase()==='HIGH').length}},[items]);
  return <><div className="section-head"><div><h1>My Work</h1><p className="muted">Your live assigned queue, ordered by urgency and due time.</p></div>{!loading&&<button className={styles.refresh} onClick={()=>void load()}>Refresh</button>}</div>
    <div className={styles.summary}>{[['Open Work',summary.open],['Overdue',summary.overdue],['Due Today',summary.dueToday],['High Priority',summary.high]].map(([label,value])=><section className="card" key={label}><span>{label}</span><b>{value}</b></section>)}</div>
    {loading?<QueueState title="Loading your queue…" detail="Retrieving current assignments and prospect details."/>:error?<QueueState title="Unable to load My Work" detail={error} action={<button className="primary" onClick={()=>void load()}>Retry</button>}/>:!items.length?<QueueState title="You’re all caught up" detail="No active assigned work items are waiting for you."/>:<Queue items={items}/>}</>;
}
function Queue({items}:{items:MyWorkItem[]}){return <section className="card"><div className="section-head"><div><h2>Active queue</h2><p className="muted">{items.length} open item{items.length===1?'':'s'}</p></div></div><div className={styles.tableWrap}><table className="table"><thead><tr><th>Affiliate</th><th>Brand</th><th>Work</th><th>Channel</th><th>Priority</th><th>Status</th><th>Due</th><th>Contact</th><th>Action</th></tr></thead><tbody>{items.map(item=><tr className={item.overdue?styles.overdueRow:''} key={item.workId}><td><strong>{item.affiliateUsername||'Unknown'}</strong><small>{item.affiliateName||'Name not provided'}</small></td><td>{item.brandName||item.brandCode||item.brandId||'—'}</td><td>{label_(item.workType)}</td><td>{label_(item.workChannel)}</td><td><Badge value={item.priority}/></td><td><Badge value={item.overdue?'OVERDUE':item.status}/></td><td>{due_(item.dueAt)}</td><td><small>{item.email||'No email'}</small><small>{item.phone||'No phone'}</small></td><td><Link className={styles.open} href={`/affiliates?workId=${encodeURIComponent(item.workId)}`}>Open</Link></td></tr>)}</tbody></table></div><div className={styles.mobileList}>{items.map(item=><article className={styles.mobileCard} key={item.workId}><div><strong>{item.affiliateUsername||'Unknown'}</strong><span>{item.affiliateName||'Name not provided'}</span></div><div className={styles.badges}><Badge value={item.priority}/><Badge value={item.overdue?'OVERDUE':item.status}/></div><dl><div><dt>Brand</dt><dd>{item.brandName||item.brandCode||item.brandId||'—'}</dd></div><div><dt>Work</dt><dd>{label_(item.workType)} · {label_(item.workChannel)}</dd></div><div><dt>Due</dt><dd>{due_(item.dueAt)}</dd></div><div><dt>Contact</dt><dd>{item.email||item.phone||'Not provided'}</dd></div></dl><Link className={styles.open} href={`/affiliates?workId=${encodeURIComponent(item.workId)}`}>Open</Link></article>)}</div></section>}
function QueueState({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}){return <section className="card empty-state"><div><div className="empty-icon">✓</div><h2>{title}</h2><p className="muted">{detail}</p>{action}</div></section>}
function Badge({value}:{value:string}){const key=String(value||'').toUpperCase();return <span className={`${styles.badge} ${key==='OVERDUE'||key==='HIGH'?styles.urgent:''}`}>{label_(key)}</span>}
function label_(value:string){return String(value||'—').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function due_(value:string){if(!value)return'No due date';const date=new Date(value);if(Number.isNaN(date.getTime()))return'Invalid date';return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(date)}
function isToday_(value:string,today:Date){if(!value)return false;const date=new Date(value);return !Number.isNaN(date.getTime())&&date.getFullYear()===today.getFullYear()&&date.getMonth()===today.getMonth()&&date.getDate()===today.getDate()}
