var USER_ROLES=['STAFF','SUPERVISOR','ADMIN'];
var STAFF_STATUSES=['ACTIVE','INACTIVE','SUSPENDED'];
var CATALOG_STATUSES=['ACTIVE','INACTIVE'];

function requiredText_(value,label,max){var text=String(value||'').trim();if(!text)throw apiError_('VALIDATION_FAILED',label+' is required.');if(text.length>(max||200))throw apiError_('VALIDATION_FAILED',label+' is too long.');return text}
function code_(value,label){var code=requiredText_(value,label,40).toUpperCase();if(!/^[A-Z0-9_-]+$/.test(code))throw apiError_('VALIDATION_FAILED',label+' may contain only letters, numbers, underscores, and hyphens.');return code}
function email_(value){var email=requiredText_(value,'Email',200);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw apiError_('VALIDATION_FAILED','Enter a valid email address.');return email}
function username_(value){var username=requiredText_(value,'Username',80);if(!/^[A-Za-z0-9._-]+$/.test(username))throw apiError_('VALIDATION_FAILED','Username contains unsupported characters.');return username}
function enum_(value,allowed,label){var normalized=String(value||'').trim().toUpperCase();if(allowed.indexOf(normalized)<0)throw apiError_('VALIDATION_FAILED','Invalid '+label+'.');return normalized}
function nonnegativeInt_(value,label,fallback){if(value===''||value===null||value===undefined){if(fallback!==undefined)return fallback;throw apiError_('VALIDATION_FAILED',label+' is required.')}var number=Number(value);if(!isFinite(number)||number<0||Math.floor(number)!==number)throw apiError_('VALIDATION_FAILED',label+' must be a non-negative whole number.');return number}
function safeStaff_(s){return {staffId:s.Staff_ID,username:s.Username,displayName:s.Display_Name,email:s.Email,role:s.Role,team:s.Team,status:s.Status,prospectTarget:s.Prospect_Target,maxManagedAffiliates:s.Max_Managed_Affiliates,lastLoginAt:s.Last_Login_At,passwordChangedAt:s.Password_Changed_At,createdAt:s.Created_At,updatedAt:s.Updated_At}}
function listStaff_(){return rows_('Staff_List').map(safeStaff_)}
function listTeams_(){return cacheRows_('Team_List',300).map(function(t){return {teamId:t.Team_ID,teamName:t.Team_Name,teamCode:t.Team_Code,status:t.Status,defaultProspectTarget:t.Default_Prospect_Target,defaultMaxManagedAffiliates:t.Default_Max_Managed_Affiliates,createdAt:t.Created_At,updatedAt:t.Updated_At}})}
function listBrands_(){return cacheRows_('Brand_List',300).map(function(b){return {brandId:b.Brand_ID,brandName:b.Brand_Name,brandCode:b.Brand_Code,market:b.Market,defaultLanguage:b.Default_Language,status:b.Status,sortOrder:b.Sort_Order,createdAt:b.Created_At,updatedAt:b.Updated_At}})}
function activeTeam_(value){var key=String(value||'').trim().toLowerCase(),team=cacheRows_('Team_List',300).filter(function(t){return (String(t.Team_ID).toLowerCase()===key||String(t.Team_Code).toLowerCase()===key)&&t.Status==='ACTIVE'})[0];if(!team)throw apiError_('VALIDATION_FAILED','Select an active team.');return team}
function uniqueCode_(sheet,column,code,excludeId,idColumn){var key=String(code).toLowerCase();if(cacheRows_(sheet,300).some(function(r){return String(r[column]).toLowerCase()===key&&String(r[idColumn])!==String(excludeId||'')}))throw apiError_('VALIDATION_FAILED',column.replace('_',' ')+' already exists.')}

function createTeam_(actor,p){requireRole_(actor,['SUPER_ADMIN']);var name=requiredText_(p.teamName,'Team name',120),teamCode=code_(p.teamCode,'Team code'),status=enum_(p.status||'ACTIVE',CATALOG_STATUSES,'team status'),target=nonnegativeInt_(p.defaultProspectTarget,'Default prospect target',0),maximum=nonnegativeInt_(p.defaultMaxManagedAffiliates,'Default max managed affiliates',0),lock=LockService.getScriptLock(),row;lock.waitLock(30000);try{clearCache_('Team_List');uniqueCode_('Team_List','Team_Code',teamCode,'','Team_ID');var t=now_();row={Team_ID:nextIdUnlocked_('Team'),Team_Name:name,Team_Code:teamCode,Status:status,Default_Prospect_Target:target,Default_Max_Managed_Affiliates:maximum,Created_At:t,Updated_At:t,Created_By:actor.Staff_ID,Updated_By:actor.Staff_ID};appendRows_('Team_List',[row])}finally{lock.releaseLock()}var safe=listTeams_().filter(function(x){return x.teamId===row.Team_ID})[0];audit_(actor,'TEAM_CREATED','Team',row.Team_ID,'',null,safe,{requestId:p.requestId});return safe}
function updateTeam_(actor,p){requireRole_(actor,['SUPER_ADMIN']);var name=requiredText_(p.teamName,'Team name',120),teamCode=code_(p.teamCode,'Team code'),status=enum_(p.status,CATALOG_STATUSES,'team status'),target=nonnegativeInt_(p.defaultProspectTarget,'Default prospect target',0),maximum=nonnegativeInt_(p.defaultMaxManagedAffiliates,'Default max managed affiliates',0),lock=LockService.getScriptLock(),before,after;lock.waitLock(30000);try{var current=findRow_('Team_List','Team_ID',p.teamId,true);if(!current)throw apiError_('NOT_FOUND','Team not found.');before={teamId:current.Team_ID,teamName:current.Team_Name,teamCode:current.Team_Code,status:current.Status,defaultProspectTarget:current.Default_Prospect_Target,defaultMaxManagedAffiliates:current.Default_Max_Managed_Affiliates,createdAt:current.Created_At,updatedAt:current.Updated_At};clearCache_('Team_List');uniqueCode_('Team_List','Team_Code',teamCode,p.teamId,'Team_ID');updateById_('Team_List','Team_ID',p.teamId,{Team_Name:name,Team_Code:teamCode,Status:status,Default_Prospect_Target:target,Default_Max_Managed_Affiliates:maximum,Updated_At:now_(),Updated_By:actor.Staff_ID});after=listTeams_().filter(function(x){return x.teamId===p.teamId})[0]}finally{lock.releaseLock()}audit_(actor,'TEAM_UPDATED','Team',p.teamId,'',before,after,{requestId:p.requestId});return after}

function createStaff_(actor,p){requireRole_(actor,['SUPER_ADMIN']);var username=username_(p.username),password=String(p.password||''),initialTeam=activeTeam_(p.team),role=enum_(p.role,USER_ROLES,'role'),status=enum_(p.status||'ACTIVE',STAFF_STATUSES,'staff status');if(password.length<12)throw apiError_('VALIDATION_FAILED','Password must contain at least 12 characters.');var passwordHash=createPasswordHash(password),displayName=requiredText_(p.displayName,'Display name',120),email=email_(p.email),target=nonnegativeInt_(p.prospectTarget,'Prospect target',Number(initialTeam.Default_Prospect_Target)||0),maximum=nonnegativeInt_(p.maxManagedAffiliates,'Max managed affiliates',Number(initialTeam.Default_Max_Managed_Affiliates)||0),lock=LockService.getScriptLock(),row;lock.waitLock(30000);try{clearCache_('Team_List');var team=activeTeam_(p.team);if(findRow_('Staff_List','Username',username,false))throw apiError_('VALIDATION_FAILED','Username already exists.');var t=now_();row={Staff_ID:nextIdUnlocked_('Staff'),Username:username,Password_Hash:passwordHash,Display_Name:displayName,Email:email,Role:role,Team:team.Team_ID,Status:status,Prospect_Target:target,Max_Managed_Affiliates:maximum,Last_Login_At:'',Password_Changed_At:t,Created_At:t,Updated_At:t,Created_By:actor.Staff_ID,Updated_By:actor.Staff_ID};appendRows_('Staff_List',[row])}finally{lock.releaseLock()}var safe=safeStaff_(row);audit_(actor,'STAFF_CREATED','Staff',row.Staff_ID,'',null,safe,{requestId:p.requestId});return safe}
function updateStaff_(actor,p){requireRole_(actor,['SUPER_ADMIN']);var current=findRow_('Staff_List','Staff_ID',p.staffId,true);if(!current)throw apiError_('NOT_FOUND','Staff member not found.');var before=safeStaff_(current),changes={Display_Name:requiredText_(p.displayName,'Display name',120),Email:email_(p.email),Prospect_Target:nonnegativeInt_(p.prospectTarget,'Prospect target',Number(current.Prospect_Target)||0),Max_Managed_Affiliates:nonnegativeInt_(p.maxManagedAffiliates,'Max managed affiliates',Number(current.Max_Managed_Affiliates)||0),Updated_At:now_(),Updated_By:actor.Staff_ID};if(current.Role==='SUPER_ADMIN'){if(p.role&&p.role!=='SUPER_ADMIN')throw apiError_('FORBIDDEN','SUPER_ADMIN role cannot be changed here.');if(p.team&&p.team!==current.Team)throw apiError_('FORBIDDEN','Root account team cannot be changed here.')}else{changes.Role=enum_(p.role||current.Role,USER_ROLES,'role');changes.Team=activeTeam_(p.team||current.Team).Team_ID}updateById_('Staff_List','Staff_ID',p.staffId,changes);var after=safeStaff_(findRow_('Staff_List','Staff_ID',p.staffId,true));audit_(actor,'STAFF_UPDATED','Staff',p.staffId,'',before,after,{requestId:p.requestId});return after}
function setStaffStatus_(actor,p){requireRole_(actor,['SUPER_ADMIN']);var status=enum_(p.status,STAFF_STATUSES,'staff status'),lock=LockService.getScriptLock(),before,after;lock.waitLock(30000);try{var current=findRow_('Staff_List','Staff_ID',p.staffId,true);if(!current)throw apiError_('NOT_FOUND','Staff member not found.');if(current.Role==='SUPER_ADMIN'&&current.Status==='ACTIVE'&&status!=='ACTIVE'){clearCache_('Staff_List');var active=rows_('Staff_List').filter(function(s){return s.Role==='SUPER_ADMIN'&&s.Status==='ACTIVE'});if(active.length<=1)throw apiError_('INVALID_STATE','The last active SUPER_ADMIN cannot be disabled.')}before=safeStaff_(current);updateById_('Staff_List','Staff_ID',p.staffId,{Status:status,Updated_At:now_(),Updated_By:actor.Staff_ID});after=safeStaff_(findRow_('Staff_List','Staff_ID',p.staffId,true))}finally{lock.releaseLock()}if(status!=='ACTIVE')revokeUserSessions_(p.staffId);audit_(actor,'STAFF_STATUS_CHANGED','Staff',p.staffId,'',before,after,{requestId:p.requestId});return after}
function resetStaffPassword_(actor,p){requireRole_(actor,['SUPER_ADMIN']);var current=findRow_('Staff_List','Staff_ID',p.staffId,true),password=String(p.newPassword||'');if(!current)throw apiError_('NOT_FOUND','Staff member not found.');if(password.length<12)throw apiError_('VALIDATION_FAILED','Password must contain at least 12 characters.');var changed=now_();updateById_('Staff_List','Staff_ID',p.staffId,{Password_Hash:createPasswordHash(password),Password_Changed_At:changed,Updated_At:changed,Updated_By:actor.Staff_ID});var revoked=revokeUserSessions_(p.staffId);audit_(actor,'STAFF_PASSWORD_RESET','Staff',p.staffId,'',null,{staffId:p.staffId,passwordChangedAt:changed,sessionsRevoked:revoked},{requestId:p.requestId});return {staffId:p.staffId,passwordChangedAt:changed,sessionsRevoked:revoked}}
function revokeUserSessions_(staffId){var lock=LockService.getScriptLock();lock.waitLock(30000);try{var s=sheet_('Sessions'),last=s.getLastRow();if(last<2)return 0;var headers=SCHEMA.Sessions,values=s.getRange(2,1,last-1,headers.length).getValues(),userIndex=headers.indexOf('User_ID'),statusIndex=headers.indexOf('Status'),revokedIndex=headers.indexOf('Revoked_At'),count=0,t=now_();for(var i=0;i<values.length;i++)if(String(values[i][userIndex])===String(staffId)&&values[i][statusIndex]==='ACTIVE'){s.getRange(i+2,revokedIndex+1,1,2).setValues([[t,'REVOKED']]);count++}clearCache_('Sessions');return count}finally{lock.releaseLock()}}

function createBrand_(actor,p){requireRole_(actor,['ADMIN','SUPER_ADMIN']);var brandCode=code_(p.brandCode,'Brand code'),name=requiredText_(p.brandName,'Brand name',120),market=requiredText_(p.market,'Market',80),language=requiredText_(p.defaultLanguage,'Default language',40),status=enum_(p.status||'ACTIVE',CATALOG_STATUSES,'brand status'),sort=nonnegativeInt_(p.sortOrder,'Sort order',0),lock=LockService.getScriptLock(),row;lock.waitLock(30000);try{clearCache_('Brand_List');uniqueCode_('Brand_List','Brand_Code',brandCode,'','Brand_ID');var t=now_();row={Brand_ID:nextIdUnlocked_('Brand'),Brand_Name:name,Brand_Code:brandCode,Market:market,Default_Language:language,Status:status,Sort_Order:sort,Created_At:t,Updated_At:t,Created_By:actor.Staff_ID,Updated_By:actor.Staff_ID};appendRows_('Brand_List',[row])}finally{lock.releaseLock()}var safe=listBrands_().filter(function(x){return x.brandId===row.Brand_ID})[0];audit_(actor,'BRAND_CREATED','Brand',row.Brand_ID,'',null,safe,{requestId:p.requestId});return safe}
function updateBrand_(actor,p){requireRole_(actor,['ADMIN','SUPER_ADMIN']);var brandCode=code_(p.brandCode,'Brand code'),name=requiredText_(p.brandName,'Brand name',120),market=requiredText_(p.market,'Market',80),language=requiredText_(p.defaultLanguage,'Default language',40),status=enum_(p.status,CATALOG_STATUSES,'brand status'),sort=nonnegativeInt_(p.sortOrder,'Sort order',0),lock=LockService.getScriptLock(),before,after;lock.waitLock(30000);try{var current=findRow_('Brand_List','Brand_ID',p.brandId,true);if(!current)throw apiError_('NOT_FOUND','Brand not found.');before={brandId:current.Brand_ID,brandName:current.Brand_Name,brandCode:current.Brand_Code,market:current.Market,defaultLanguage:current.Default_Language,status:current.Status,sortOrder:current.Sort_Order,createdAt:current.Created_At,updatedAt:current.Updated_At};clearCache_('Brand_List');uniqueCode_('Brand_List','Brand_Code',brandCode,p.brandId,'Brand_ID');updateById_('Brand_List','Brand_ID',p.brandId,{Brand_Name:name,Brand_Code:brandCode,Market:market,Default_Language:language,Status:status,Sort_Order:sort,Updated_At:now_(),Updated_By:actor.Staff_ID});after=listBrands_().filter(function(x){return x.brandId===p.brandId})[0]}finally{lock.releaseLock()}audit_(actor,'BRAND_UPDATED','Brand',p.brandId,'',before,after,{requestId:p.requestId});return after}
