function doGet(){return json_({ok:false,error:{code:'METHOD_NOT_ALLOWED',message:'Use POST.'}})}
function doPost(e){
  var totalStart=Date.now(),parseStart=Date.now(),request={};beginRequest_();
  try{request=JSON.parse(e&&e.postData&&e.postData.contents||'{}');var parseMs=Date.now()-parseStart,data=route_(request);console.log(JSON.stringify({event:'api_timing',action:String(request.action||''),requestParseMs:parseMs,totalMs:Date.now()-totalStart}));return json_({ok:true,data:data})}
  catch(err){console.error(err&&err.internalMessage||err&&err.stack||err);console.log(JSON.stringify({event:'api_timing',action:String(request.action||''),failed:true,totalMs:Date.now()-totalStart}));var safe=['INVALID_REQUEST','INVALID_CREDENTIALS','LOGIN_LIMITED','UNAUTHENTICATED','SESSION_EXPIRED','FORBIDDEN','NOT_FOUND','INVALID_STATE','INVALID_STATUS','VALIDATION_FAILED','UNKNOWN_ACTION'];return json_({ok:false,error:{code:safe.indexOf(err.code)>=0?err.code:'INTERNAL_ERROR',message:safe.indexOf(err.code)>=0?err.message:'The request could not be completed.'}})}
}
function route_(request){
  var action=String(request.action||''),p=request.payload||{};p.requestId=String(request.requestId||Utilities.getUuid());if(action==='login')return login_(p);
  var auth=sessionUser_(request.token),u=auth.staff,session=auth.session;
  var authenticated={logout:function(){return logout_(request.token,u,session,p.requestId)},currentUser:function(){return publicUser_(u)},validateSession:function(){return {valid:true,expiresAt:session.Expires_At}}};if(authenticated[action])return authenticated[action]();
  var staffActions={getMyWork:function(){return myWork_(u,p)},getAffiliate:function(){return affiliate_(u,p)},startWork:function(){return startWork_(u,p)},recordContactAttempt:function(){return contact_(u,p)},markTelegramConnected:function(){return telegram_(u,p)},completeWork:function(){return completeWork_(u,p)},createFollowup:function(){return followup_(u,p)},logInteraction:function(){return interaction_(u,p)}};if(staffActions[action])return staffActions[action]();
  requireRole_(u,['ADMIN','SUPER_ADMIN']);var adminActions={listStaff:function(){return listStaff_()},createStaff:function(){return createStaff_(u,p)},updateStaff:function(){return updateStaff_(u,p)},setStaffStatus:function(){return setStaffStatus_(u,p)},resetStaffPassword:function(){return resetStaffPassword_(u,p)},listTeams:function(){return listTeams_()},createTeam:function(){return createTeam_(u,p)},updateTeam:function(){return updateTeam_(u,p)},listBrands:function(){return listBrands_()},createBrand:function(){return createBrand_(u,p)},updateBrand:function(){return updateBrand_(u,p)},validateAffiliateImport:function(){return validateImport_(u,p)},commitAffiliateImport:function(){return importAffiliates_(u,p)},assignAffiliate:function(){return assign_(u,p)},transferAffiliate:function(){return transfer_(u,p)},archiveAffiliate:function(){return archive_(u,p)},reopenAffiliate:function(){return reopen_(u,p)}};
  if(!adminActions[action])throw apiError_('UNKNOWN_ACTION','Unknown action.','Unknown action: '+action);return adminActions[action]();
}
function json_(value){return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON)}
function apiError_(code,publicMessage,internalMessage){var e=new Error(publicMessage);e.code=code;e.internalMessage=internalMessage||publicMessage;return e}
