var IMPORT_LIMIT=500;
function importKey_(value){return String(value||'').trim().toLowerCase()}
function cleanImportRow_(row){return {username:String(row&&row.username||'').trim(),fullName:String(row&&row.fullName||'').trim(),email:String(row&&row.email||'').trim(),phone:String(row&&row.phone||'').trim()}}
function activeImportBrand_(brandId){var brand=rows_('Brand_List').filter(function(b){return String(b.Brand_ID)===String(brandId)&&b.Status==='ACTIVE'})[0];if(!brand)throw apiError_('VALIDATION_FAILED','Select an active brand.');return brand}
function activeImportStaff_(staffId){var staff=rows_('Staff_List').filter(function(s){return String(s.Staff_ID)===String(staffId)&&s.Status==='ACTIVE'})[0];if(!staff)throw apiError_('VALIDATION_FAILED','Select an active staff member.');var teamKey=importKey_(staff.Team),team=rows_('Team_List').filter(function(t){return t.Status==='ACTIVE'&&(importKey_(t.Team_ID)===teamKey||importKey_(t.Team_Code)===teamKey)})[0];if(!team)throw apiError_('VALIDATION_FAILED','Selected staff member must belong to an active team.');return staff}
function importConfig_(p){var destination=String(p.destination||'').toUpperCase(),mode=String(p.mode||'NEW_PROSPECTS').toUpperCase();if(mode!=='NEW_PROSPECTS')throw apiError_('VALIDATION_FAILED','Only New Prospects is currently available.');if(['STAFF','POOL'].indexOf(destination)<0)throw apiError_('VALIDATION_FAILED','Select an import destination.');var brand=activeImportBrand_(p.brandId),staff=destination==='STAFF'?activeImportStaff_(p.staffId):null;return {destination:destination,mode:mode,brand:brand,staff:staff}}
function duplicateKeys_(rows,field){var counts={},duplicates={};rows.forEach(function(r){var key=importKey_(r[field]);if(key)counts[key]=(counts[key]||0)+1});Object.keys(counts).forEach(function(key){if(counts[key]>1)duplicates[key]=true});return duplicates}
function validateImport_(u,p){
  requireRole_(u,['ADMIN','SUPER_ADMIN']);var cfg=importConfig_(p),input=p.rows||[];if(!Array.isArray(input)||!input.length)throw apiError_('VALIDATION_FAILED','Paste at least one affiliate row.');if(input.length>IMPORT_LIMIT)throw apiError_('VALIDATION_FAILED','Imports are limited to '+IMPORT_LIMIT+' rows.');var cleaned=input.map(cleanImportRow_),dupUsers=duplicateKeys_(cleaned,'username'),dupEmails=duplicateKeys_(cleaned,'email'),dupPhones=duplicateKeys_(cleaned,'phone'),affiliates=rows_('Affiliates'),pool=rows_('Affiliate_Pool'),assignments=rows_('Assignments'),byUser={},byEmail={},byPhone={},poolUsers={};
  affiliates.forEach(function(a){var uk=importKey_(a.Affiliate_Username),ek=importKey_(a.Email),pk=importKey_(a.Phone);if(uk)byUser[uk]=a;if(ek)(byEmail[ek]||(byEmail[ek]=[])).push(a);if(pk)(byPhone[pk]||(byPhone[pk]=[])).push(a)});pool.forEach(function(r){var key=importKey_(r.Affiliate_Username);if(key)poolUsers[key]=r});var activeAssignments={};assignments.forEach(function(a){if(a.Status==='ACTIVE')activeAssignments[a.Affiliate_ID]=true});
  var summary={totalRows:cleaned.length,validRows:0,invalidRows:0,existingAffiliates:0,duplicateRows:0,duplicateUsernames:0,duplicateEmails:0,duplicatePhones:0,missingContact:0,invalidContactFormat:0,existingActiveAssignment:0,archivedMatches:0};
  var rows=cleaned.map(function(r,i){var reasons=[],uk=importKey_(r.username),ek=importKey_(r.email),pk=importKey_(r.phone),existing=uk&&byUser[uk];if(!r.username)reasons.push('Affiliate username is required.');if(!r.email&&!r.phone){reasons.push('Email or phone number is required.');summary.missingContact++}if(r.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(r.email)){reasons.push('Email format is invalid.');summary.invalidContactFormat++}if(r.phone&&!/^\+?[0-9() .-]{5,30}$/.test(r.phone)){reasons.push('Phone format is invalid.');summary.invalidContactFormat++}if(uk&&dupUsers[uk]){reasons.push('Duplicate username in this upload.');summary.duplicateUsernames++}if(ek&&dupEmails[ek]){reasons.push('Duplicate email in this upload.');summary.duplicateEmails++}if(pk&&dupPhones[pk]){reasons.push('Duplicate phone in this upload.');summary.duplicatePhones++}if(existing){summary.existingAffiliates++;reasons.push(existing.Archive_Status==='ARCHIVED'?'Username matches an archived/closed affiliate.':'Username already exists in Affiliates.');if(existing.Archive_Status==='ARCHIVED')summary.archivedMatches++;if(activeAssignments[existing.Affiliate_ID]){reasons.push('Affiliate already has an active assignment.');summary.existingActiveAssignment++}}if(uk&&poolUsers[uk])reasons.push('Username already exists in Affiliate Pool.');if(!existing&&ek&&byEmail[ek])reasons.push('Email is already used by another affiliate; review required.');if(!existing&&pk&&byPhone[pk])reasons.push('Phone is already used by another affiliate; review required.');if(reasons.length){summary.invalidRows++;if(dupUsers[uk]||dupEmails[ek]||dupPhones[pk]||poolUsers[uk])summary.duplicateRows++}else summary.validRows++;return {row:i+1,username:r.username,fullName:r.fullName,email:r.email,phone:r.phone,status:reasons.length?'INVALID':'VALID',reasons:reasons}});return {configuration:{brandId:cfg.brand.Brand_ID,brandName:cfg.brand.Brand_Name,brandCode:cfg.brand.Brand_Code,destination:cfg.destination,staffId:cfg.staff&&cfg.staff.Staff_ID||'',staffName:cfg.staff&&cfg.staff.Display_Name||'',mode:cfg.mode},summary:summary,rows:rows,limit:IMPORT_LIMIT};
}
function importBatchRow_(id,cfg,summary,u,t){return {Import_Batch_ID:id,Import_Type:cfg.destination==='STAFF'?'NEW_PROSPECT_DIRECT':'NEW_PROSPECT_POOL',File_Name:'PASTE_'+t.replace(/[-:.TZ]/g,''),Brand_ID:cfg.brand.Brand_ID,Assigned_Staff_ID:cfg.staff&&cfg.staff.Staff_ID||'',Market:cfg.brand.Market||'',Total_Rows:summary.totalRows,Valid_Rows:summary.validRows,Imported_Rows:0,Duplicate_Rows:summary.duplicateRows,Existing_Rows:summary.existingAffiliates,Invalid_Rows:summary.invalidRows,Archived_Matches:summary.archivedMatches,Status:'IN_PROGRESS',Started_At:t,Completed_At:'',Imported_By:u.Staff_ID,Notes:'Validated server-side at commit'} }
function importAffiliates_(u,p){
  requireRole_(u,['ADMIN','SUPER_ADMIN']);var lock=LockService.getScriptLock();lock.waitLock(30000);var batchId='',createdAffiliates=0,assignmentsCreated=0,workItemsCreated=0,poolRowsAdded=0,summary,cfg,batchWritten=false,t=now_();
  try{clearCache_('Affiliates');clearCache_('Affiliate_Pool');clearCache_('Assignments');clearCache_('Brand_List');clearCache_('Staff_List');clearCache_('Team_List');var result=validateImport_(u,p);summary=result.summary;cfg=importConfig_(p);if(!summary.validRows)throw apiError_('VALIDATION_FAILED','No valid rows are available to commit.');var valid=result.rows.filter(function(r){return r.status==='VALID'}),batchIds=reserveIdsUnlocked_('Import',1);batchId=batchIds[0];appendRows_('Import_Batches',[importBatchRow_(batchId,cfg,summary,u,t)]);batchWritten=true;
    if(cfg.destination==='POOL'){var poolRows=valid.map(function(r){return {Affiliate_Username:r.username,Full_Name:r.fullName,Email:r.email,Phone_Number:r.phone,Brand:cfg.brand.Brand_Code}});appendRows_('Affiliate_Pool',poolRows);poolRowsAdded=poolRows.length}
    else{var affIds=reserveIdsUnlocked_('Affiliate',valid.length),assignmentIds=reserveIdsUnlocked_('Assignment',valid.length),workIds=reserveIdsUnlocked_('Work',valid.length),sla=Math.max(1,Number(config_('FIRST_CONTACT_SLA_HOURS'))||24),due=new Date(Date.now()+sla*3600000).toISOString(),affiliates=[],assignmentRows=[],workRows=[];valid.forEach(function(r,i){var affiliateId=affIds[i],assignmentId=assignmentIds[i];affiliates.push({Affiliate_ID:affiliateId,Affiliate_Username:r.username,Email:r.email,Phone:r.phone,Brand_ID:cfg.brand.Brand_ID,Market:cfg.brand.Market||'',Country:'',Language:cfg.brand.Default_Language||'',Affiliate_Name:r.fullName,Preferred_Channel:'',Telegram_Username:'',Telegram_Status:'NOT_CONNECTED',Lifecycle_Status:'ASSIGNED',Health_Status:'UNASSESSED',Priority:'NORMAL',Prospect_Status:'NEW',Archive_Status:'ACTIVE',Archive_Reason:'',First_Added_At:t,Last_Contact_At:'',Last_Meaningful_Contact_At:'',Telegram_Connected_At:'',Archived_At:'',Created_At:t,Updated_At:t,Created_By:u.Staff_ID,Updated_By:u.Staff_ID});assignmentRows.push({Assignment_ID:assignmentId,Affiliate_ID:affiliateId,Staff_ID:cfg.staff.Staff_ID,Brand_ID:cfg.brand.Brand_ID,Assignment_Type:'PROSPECT',Status:'ACTIVE',Assigned_At:t,Activated_At:t,Ended_At:'',End_Reason:'',Previous_Assignment_ID:'',Import_Batch_ID:batchId,Assigned_By:u.Staff_ID,Created_At:t,Updated_At:t});workRows.push({Work_ID:workIds[i],Affiliate_ID:affiliateId,Assignment_ID:assignmentId,Staff_ID:cfg.staff.Staff_ID,Work_Type:'FIRST_CONTACT',Work_Channel:'CALL',Priority:'NORMAL',Status:'PENDING',Title:'Initial affiliate contact',Reason:'NEW_PROSPECT',Generated_By:'SYSTEM_IMPORT',Assigned_At:t,Due_At:due,Started_At:'',Completed_At:'',Outcome:'',Completion_Notes:'',Next_Action_At:'',SLA_Minutes:sla*60,Escalation_Level:0,Is_Auto_Generated:true,Parent_Work_ID:'',Created_At:t,Updated_At:t})});appendRows_('Affiliates',affiliates);createdAffiliates=affiliates.length;appendRows_('Assignments',assignmentRows);assignmentsCreated=assignmentRows.length;appendRows_('Work_Items',workRows);workItemsCreated=workRows.length}
    updateById_('Import_Batches','Import_Batch_ID',batchId,{Imported_Rows:cfg.destination==='POOL'?poolRowsAdded:createdAffiliates,Status:summary.invalidRows?'PARTIAL':'COMPLETED',Completed_At:now_(),Notes:'Committed valid rows; invalid rows skipped'});
  }catch(err){if(batchWritten)try{updateById_('Import_Batches','Import_Batch_ID',batchId,{Imported_Rows:cfg&&cfg.destination==='POOL'?poolRowsAdded:createdAffiliates,Status:(createdAffiliates||poolRowsAdded)?'PARTIAL':'FAILED',Completed_At:now_(),Notes:'Commit stopped: '+String(err.message||'unknown error').slice(0,300)})}catch(batchErr){console.error(batchErr)}throw err}finally{lock.releaseLock()}
  var counts={importedAffiliates:createdAffiliates,assignmentsCreated:assignmentsCreated,workItemsCreated:workItemsCreated,poolRowsAdded:poolRowsAdded,skippedRows:summary.invalidRows,invalidRows:summary.invalidRows};audit_(u,'AFFILIATE_IMPORT_COMMITTED','Import',batchId,'',null,{Import_Batch_ID:batchId,destination:cfg.destination,Brand_ID:cfg.brand.Brand_ID,Staff_ID:cfg.staff&&cfg.staff.Staff_ID||'',counts:counts},{requestId:p.requestId});counts.importBatchId=batchId;return counts;
}
