var PERFORMANCE_DECLINE_PERCENT_=30;
var PERFORMANCE_FRESH_MS_=30*24*60*60*1000;
var PERFORMANCE_SOURCE_KEYS_=['registeredUsers','ftd','activePlayers','totalDeposit','totalWithdrawal','totalTurnover','profitLoss'];
function performanceIdPart_(value){return String(value===null||value===undefined?'':value).trim().toUpperCase()}
function performancePeriod_(value){var p=String(value||'').trim();if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test(p))throw apiError_('VALIDATION_FAILED','Choose a valid performance month.');return p}
function performanceStoredPeriod_(value){if(value instanceof Date&&!isNaN(value.getTime()))return value.getFullYear()+'-'+String(value.getMonth()+1).padStart(2,'0');var text=String(value===null||value===undefined?'':value).trim(),match=text.match(/^(20\d{2})-(0[1-9]|1[0-2])(?:-\d{2})?(?:T.*)?$/);if(match)return match[1]+'-'+match[2];var parsed=new Date(text);return text&&!isNaN(parsed.getTime())?parsed.getFullYear()+'-'+String(parsed.getMonth()+1).padStart(2,'0'):''}
function performanceKey_(affiliateId,brandId,period){return performanceIdPart_(affiliateId)+'|'+performanceIdPart_(brandId)+'|'+performanceStoredPeriod_(period)}
function performanceRowKey_(row){var year=Number(row.Year),month=Number(row.Month),period=row.Period instanceof Date&&year>=2000&&month>=1&&month<=12?year+'-'+String(month).padStart(2,'0'):row.Period;return performanceKey_(row.Affiliate_ID,row.Brand_ID,period)}
function previousPeriod_(p){var parts=p.split('-'),d=new Date(Date.UTC(Number(parts[0]),Number(parts[1])-2,1));return d.getUTCFullYear()+'-'+String(d.getUTCMonth()+1).padStart(2,'0')}
function performanceNumber_(value,label,integer,negative){if(value===''||value===null||value===undefined||typeof value==='boolean')throw apiError_('VALIDATION_FAILED',label+' is required.');var n=Number(value);if(!isFinite(n)||Math.abs(n)>1e15||integer&&Math.floor(n)!==n||!negative&&n<0)throw apiError_('VALIDATION_FAILED','Enter a valid '+label+'.');return n}
function performanceValues_(p){return {Registrations:performanceNumber_(p.registeredUsers,'registered users',true,false),FTD:performanceNumber_(p.ftd,'first deposits',true,false),Active_Players:performanceNumber_(p.activePlayers,'active players',true,false),Deposit_Amount:performanceNumber_(p.totalDeposit,'total deposit',false,false),Withdrawal_Amount:performanceNumber_(p.totalWithdrawal,'total withdrawal',false,false),Turnover:performanceNumber_(p.totalTurnover,'total turnover',false,false),Revenue_NGR:performanceNumber_(p.profitLoss,'profit and loss',false,true)}}
function performanceMetrics_(r){var registrations=Number(r&&r.Registrations)||0,ftd=Number(r&&r.FTD)||0,active=Number(r&&r.Active_Players)||0,deposit=Number(r&&r.Deposit_Amount)||0,withdrawal=Number(r&&r.Withdrawal_Amount)||0,turnover=Number(r&&r.Turnover)||0,pnl=Number(r&&r.Revenue_NGR)||0;return {registeredUsers:registrations,ftd:ftd,activePlayers:active,totalDeposit:deposit,totalWithdrawal:withdrawal,totalTurnover:turnover,profitLoss:pnl,netCashFlow:deposit-withdrawal,ftdRate:registrations?ftd/registrations*100:0,activeRate:registrations?active/registrations*100:0,averageDepositPerActive:active?deposit/active:0,turnoverPerActive:active?turnover/active:0}}
function performanceChange_(current,previous){if(previous===0)return {direction:current===0?'NO_CHANGE':'NEW',percent:null};var percent=(current-previous)/Math.abs(previous)*100;return {direction:percent>0?'INCREASE':percent<0?'DECREASE':'NO_CHANGE',percent:percent}}
function performanceReasons_(current,previous){if(!current)return ['NOT_UPDATED'];if(!previous)return [];var reasons=[],pairs=[['activePlayers','ACTIVE_PLAYERS_DOWN'],['ftd','FTD_DOWN'],['totalDeposit','DEPOSIT_DOWN'],['totalTurnover','TURNOVER_DOWN']];pairs.forEach(function(x){var before=previous[x[0]],now=current[x[0]];if(before>0&&(before-now)/before*100>=PERFORMANCE_DECLINE_PERCENT_)reasons.push(x[1])});if(previous.activePlayers>0&&current.activePlayers===0)reasons.push('ZERO_ACTIVE_PLAYERS');return reasons}
function performanceIndex_(rows){var groups={};rows.forEach(function(r){var key=performanceRowKey_(r);if(!key.split('|')[2])return;(groups[key]||(groups[key]=[])).push(r)});return groups}
function performanceIndexCached_(){return typeof requestMemo_==='function'?requestMemo_('performance:index',function(){return performanceIndex_(rows_('Monthly_Performance'))}):performanceIndex_(rows_('Monthly_Performance'))}
function performanceGroup_(groups,affiliateId,brandId,period){return groups[performanceKey_(affiliateId,brandId,period)]||[]}
function performanceFreshnessIndex_(groups){var build=function(){var index={};Object.keys(groups).forEach(function(key){var parts=key.split('|'),scope=parts[0]+'|'+parts[1],group=groups[key],groupLatest=-Infinity;group.forEach(function(row){var timestamp=new Date(row.Imported_At).getTime();if(isFinite(timestamp)&&timestamp>groupLatest)groupLatest=timestamp});var current=index[scope];if(!current||groupLatest>current.latest)index[scope]={latest:groupLatest,conflict:group.length>1};else if(groupLatest===current.latest&&groupLatest>-Infinity&&group.length>1)current.conflict=true});return index};return typeof requestMemo_==='function'?requestMemo_('performance:freshness-index',build):build()}
function performanceFreshness_(groups,affiliateId,brandId,nowMs,selectedConflict,index){if(selectedConflict)return {freshnessStatus:'REVIEW_REQUIRED',lastSuccessfulUpdate:'',updateDueAt:'',performanceUpdateDue:false};index=index||performanceFreshnessIndex_(groups);var latestEntry=index[performanceIdPart_(affiliateId)+'|'+performanceIdPart_(brandId)];if(latestEntry&&latestEntry.conflict)return {freshnessStatus:'REVIEW_REQUIRED',lastSuccessfulUpdate:'',updateDueAt:'',performanceUpdateDue:false};var latest=latestEntry?latestEntry.latest:-Infinity;if(latest===-Infinity)return {freshnessStatus:'NO_UPDATE',lastSuccessfulUpdate:'',updateDueAt:'',performanceUpdateDue:true};var dueAt=latest+PERFORMANCE_FRESH_MS_,due=Number(nowMs)>=dueAt;return {freshnessStatus:due?'UPDATE_DUE':'FRESH',lastSuccessfulUpdate:new Date(latest).toISOString(),updateDueAt:new Date(dueAt).toISOString(),performanceUpdateDue:due}}
function performanceMaps_(){var build=function(){var affiliates={},brands={},staff={},teams={},active=[],groups=performanceIndexCached_();rows_('Affiliates').forEach(function(a){affiliates[performanceIdPart_(a.Affiliate_ID)]=a});rows_('Brand_List').forEach(function(b){brands[performanceIdPart_(b.Brand_ID)]=b});rows_('Staff_List').forEach(function(s){staff[performanceIdPart_(s.Staff_ID)]=s});rows_('Team_List').forEach(function(t){teams[performanceIdPart_(t.Team_ID)]=t});rows_('Assignments').forEach(function(a){if(String(a.Status).trim().toUpperCase()==='ACTIVE')active.push(a)});return {affiliates:affiliates,brands:brands,staff:staff,teams:teams,active:active,groups:groups}};return typeof requestMemo_==='function'?requestMemo_('performance:maps',build):build()}
function performanceWorkspace_(user,p){
  var period=performancePeriod_(p.period),previous=previousPeriod_(period),m=performanceMaps_(),admin=['ADMIN','SUPER_ADMIN'].indexOf(user.Role)>=0;if(!admin)requireRole_(user,['STAFF']);
  var assignments=m.active.filter(function(a){if(!admin)return performanceIdPart_(a.Staff_ID)===performanceIdPart_(user.Staff_ID);if(p.staffId&&performanceIdPart_(a.Staff_ID)!==performanceIdPart_(p.staffId))return false;var s=m.staff[performanceIdPart_(a.Staff_ID)]||{};if(p.teamId&&performanceIdPart_(s.Team)!==performanceIdPart_(p.teamId))return false;if(p.brandId&&performanceIdPart_(a.Brand_ID)!==performanceIdPart_(p.brandId))return false;return true});
  var summary={assignedAffiliates:0,updated:0,notUpdated:0,needsAttention:0,dataConflicts:0,fresh:0,updateDue:0,registeredUsers:0,ftd:0,activePlayers:0,totalDeposit:0,totalWithdrawal:0,totalTurnover:0,profitLoss:0},staffRows={},nowMs=Date.now(),freshnessIndex=performanceFreshnessIndex_(m.groups);
  var items=assignments.map(function(a){
    var affiliate=m.affiliates[performanceIdPart_(a.Affiliate_ID)];if(!affiliate)return null;var brandId=String(a.Brand_ID||affiliate.Brand_ID),currentGroup=performanceGroup_(m.groups,affiliate.Affiliate_ID,brandId,period),priorGroup=performanceGroup_(m.groups,affiliate.Affiliate_ID,brandId,previous),conflict=currentGroup.length>1,priorConflict=priorGroup.length>1,row=currentGroup.length===1?currentGroup[0]:null,prior=priorGroup.length===1?priorGroup[0]:null,metrics=row?performanceMetrics_(row):null,priorMetrics=prior?performanceMetrics_(prior):null,freshness=performanceFreshness_(m.groups,affiliate.Affiliate_ID,brandId,nowMs,conflict,freshnessIndex),reasons=conflict?['PERFORMANCE_DATA_CONFLICT']:performanceReasons_(metrics,priorMetrics),comparisons={};if(freshness.performanceUpdateDue&&reasons.indexOf('PERFORMANCE_UPDATE_DUE')<0)reasons.push('PERFORMANCE_UPDATE_DUE');
    if(priorConflict&&!conflict&&metrics)reasons.push('PREVIOUS_PERIOD_DATA_CONFLICT');if(metrics&&priorMetrics)PERFORMANCE_SOURCE_KEYS_.forEach(function(k){comparisons[k]=performanceChange_(metrics[k],priorMetrics[k])});var status=conflict?'DATA_CONFLICT':!row?'NOT_UPDATED':reasons.length?'NEEDS_ATTENTION':'HEALTHY';
    summary.assignedAffiliates++;if(row)summary.updated++;else summary.notUpdated++;if(conflict)summary.dataConflicts++;if(freshness.freshnessStatus==='FRESH')summary.fresh++;if(freshness.performanceUpdateDue)summary.updateDue++;if(reasons.length)summary.needsAttention++;if(metrics)PERFORMANCE_SOURCE_KEYS_.forEach(function(k){summary[k]+=metrics[k]});
    var staffKey=performanceIdPart_(a.Staff_ID),s=m.staff[staffKey]||{},sr=staffRows[staffKey]||(staffRows[staffKey]={staffId:String(a.Staff_ID),staffName:s.Display_Name||s.Username||'',teamId:String(s.Team||''),teamName:(m.teams[performanceIdPart_(s.Team)]||{}).Team_Name||'',assignedAffiliates:0,updated:0,needsAttention:0,dataConflicts:0,updateDue:0,registeredUsers:0,ftd:0,activePlayers:0,totalDeposit:0,totalWithdrawal:0,totalTurnover:0,profitLoss:0});sr.assignedAffiliates++;if(row)sr.updated++;if(reasons.length)sr.needsAttention++;if(conflict)sr.dataConflicts++;if(freshness.performanceUpdateDue)sr.updateDue++;if(metrics)PERFORMANCE_SOURCE_KEYS_.forEach(function(k){sr[k]+=metrics[k]});
    return {affiliateId:String(affiliate.Affiliate_ID),affiliateUsername:String(affiliate.Affiliate_Username||''),affiliateName:String(affiliate.Affiliate_Name||''),brandId:brandId,brandName:String((m.brands[performanceIdPart_(brandId)]||{}).Brand_Name||''),staffId:String(a.Staff_ID),staffName:sr.staffName,period:period,status:status,performanceId:row&&String(row.Performance_ID)||'',metrics:metrics,previous:priorMetrics,comparisons:comparisons,needsAttention:reasons.length>0,attentionReasons:reasons,lastUpdated:row&&String(row.Imported_At||'')||'',lastSuccessfulUpdate:freshness.lastSuccessfulUpdate,updateDueAt:freshness.updateDueAt,freshnessStatus:freshness.freshnessStatus,performanceUpdateDue:freshness.performanceUpdateDue,conflict:conflict?{count:currentGroup.length,recordIds:admin?currentGroup.map(function(x){return String(x.Performance_ID)}):[]}:null};
  }).filter(Boolean);
  var staffComparisons=Object.keys(staffRows).map(function(k){var s=staffRows[k],n=s.assignedAffiliates||1;s.updatedPercent=s.updated/n*100;s.ftdPerAffiliate=s.ftd/n;s.activePlayersPerAffiliate=s.activePlayers/n;s.depositPerAffiliate=s.totalDeposit/n;s.turnoverPerAffiliate=s.totalTurnover/n;return s});
  var options=admin?{staff:Object.keys(m.staff).map(function(k){var s=m.staff[k];return {staffId:String(s.Staff_ID),displayName:s.Display_Name||s.Username||'',teamId:String(s.Team||'')}}),teams:Object.keys(m.teams).map(function(k){return {teamId:String(m.teams[k].Team_ID),teamName:m.teams[k].Team_Name||''}}),brands:Object.keys(m.brands).map(function(k){return {brandId:String(m.brands[k].Brand_ID),brandName:m.brands[k].Brand_Name||''}})}:{staff:[],teams:[],brands:[]};
  return {period:period,canManage:admin,items:items,summary:summary,staff:admin?staffComparisons:[],options:options};
}
function saveAffiliatePerformance_(user,p){
  requireRole_(user,['STAFF']);var period=performancePeriod_(p.period),values=performanceValues_(p),allowed={affiliateId:true,period:true,registeredUsers:true,ftd:true,activePlayers:true,totalDeposit:true,totalWithdrawal:true,totalTurnover:true,profitLoss:true,staffId:true,assignmentId:true,brandId:true,requestId:true};Object.keys(p).forEach(function(k){if(!allowed[k])throw apiError_('VALIDATION_FAILED','Unsupported performance field.');});
  var lock=LockService.getScriptLock(),row,before=null,changed=[],created=false;lock.waitLock(30000);try{
    ['Affiliates','Assignments','Monthly_Performance'].forEach(clearCache_);var m=performanceMaps_(),affiliate=m.affiliates[performanceIdPart_(p.affiliateId)];if(!affiliate)throw apiError_('NOT_FOUND','Affiliate not found.');var assignment=m.active.filter(function(a){return performanceIdPart_(a.Affiliate_ID)===performanceIdPart_(affiliate.Affiliate_ID)&&performanceIdPart_(a.Staff_ID)===performanceIdPart_(user.Staff_ID)})[0];if(!assignment)throw apiError_('FORBIDDEN','This affiliate is not in your current active assignment scope.');var brandId=String(assignment.Brand_ID||affiliate.Brand_ID),group=performanceGroup_(m.groups,affiliate.Affiliate_ID,brandId,period);if(group.length>1)throw apiError_('PERFORMANCE_DATA_CONFLICT','Performance record requires administrator review.');row=group[0]||null;
    if(row){var old={},next={};Object.keys(values).forEach(function(k){if(Number(row[k]||0)!==values[k]){changed.push(k);old[k]=Number(row[k]||0);next[k]=values[k]}});if(!changed.length)throw apiError_('INVALID_STATE','No performance changes were provided.');before={fields:changed,values:old};values.Conversion_Rate=values.Registrations?values.FTD/values.Registrations*100:0;values.Imported_At=now_();updateById_('Monthly_Performance','Performance_ID',row.Performance_ID,values);row=Object.assign({},row,values);row._new={fields:changed,values:next}}
    else{created=true;changed=Object.keys(values);var parts=period.split('-');row=Object.assign({Performance_ID:nextIdUnlocked_('Performance'),Affiliate_ID:affiliate.Affiliate_ID,Brand_ID:brandId,Period:period,Year:Number(parts[0]),Month:Number(parts[1]),Deposits_Count:'',Commission:'',Previous_FTD:'',FTD_Change_Percent:'',Previous_NGR:'',NGR_Change_Percent:'',Import_Batch_ID:'',Imported_At:now_(),Created_By:user.Staff_ID},values);row.Conversion_Rate=row.Registrations?row.FTD/row.Registrations*100:0;appendRows_('Monthly_Performance',[row]);row._new={fields:changed,values:values}}
  }finally{lock.releaseLock()}
  audit_(user,created?'AFFILIATE_PERFORMANCE_CREATED':'AFFILIATE_PERFORMANCE_UPDATED','Performance',row.Performance_ID,row.Affiliate_ID,before,{performanceId:row.Performance_ID,affiliateId:row.Affiliate_ID,brandId:row.Brand_ID,period:period,fields:row._new.fields,values:row._new.values},{requestId:p.requestId});delete row._new;return {performanceId:String(row.Performance_ID),affiliateId:String(row.Affiliate_ID),brandId:String(row.Brand_ID),period:period,created:created,metrics:performanceMetrics_(row)};
}
