function ownedAffiliateIds_(user){return rows_('Assignments').filter(function(a){return a.Staff_ID===user.Staff_ID&&a.Status==='ACTIVE'}).map(function(a){return a.Affiliate_ID})}
function assertOwned_(user,affiliateId){if(['ADMIN','SUPER_ADMIN','SUPERVISOR'].indexOf(user.Role)>=0)return;if(ownedAffiliateIds_(user).indexOf(affiliateId)<0)throw apiError_('FORBIDDEN','Affiliate is not assigned to you.')}
function myWork_(user,p){var items=rows_('Work_Items').filter(function(w){return w.Staff_ID===user.Staff_ID&&['PENDING','IN_PROGRESS','OVERDUE'].indexOf(w.Status)>=0});items.sort(function(a,b){return Number(b.Priority)-Number(a.Priority)||new Date(a.Due_At)-new Date(b.Due_At)});return page_(items,p)}
function affiliate_(user,p){assertOwned_(user,p.affiliateId);var aff=rows_('Affiliates').filter(function(x){return x.Affiliate_ID===p.affiliateId})[0];if(!aff)throw apiError_('NOT_FOUND','Affiliate not found.');return {affiliate:aff,assignments:rows_('Assignments').filter(function(x){return x.Affiliate_ID===p.affiliateId}),contacts:rows_('Contact_Attempts').filter(function(x){return x.Affiliate_ID===p.affiliateId}).slice(-100),interactions:rows_('Interactions').filter(function(x){return x.Affiliate_ID===p.affiliateId}).slice(-100)} }
function assertWork_(u,id){var w=rows_('Work_Items').filter(function(x){return x.Work_Item_ID===id})[0];if(!w)throw apiError_('NOT_FOUND','Work item not found.');if(u.Role==='STAFF'&&w.Staff_ID!==u.Staff_ID)throw apiError_('FORBIDDEN','Work item is not assigned to you.');return w}
function startWork_(u,p){var w=assertWork_(u,p.workItemId);if(w.Status!=='PENDING'&&w.Status!=='OVERDUE')throw apiError_('INVALID_STATE','Work item cannot be started.');var before=updateById_('Work_Items','Work_Item_ID',w.Work_Item_ID,{Status:'IN_PROGRESS',Started_At:now_(),Updated_At:now_()});updateById_('Affiliates','Affiliate_ID',w.Affiliate_ID,{Lifecycle_Status:'CONTACTING',Updated_At:now_()});audit_(u,'START_WORK','Work_Item',w.Work_Item_ID,before,{Status:'IN_PROGRESS'},p.requestId);return {workItemId:w.Work_Item_ID,status:'IN_PROGRESS'}}
function contact_(u,p){var w=assertWork_(u,p.workItemId);assertOwned_(u,w.Affiliate_ID);var row={Contact_Attempt_ID:newId_('Contact_Attempts'),Affiliate_ID:w.Affiliate_ID,Work_Item_ID:w.Work_Item_ID,Staff_ID:u.Staff_ID,Channel:p.channel,Outcome:p.outcome,Contacted_At:p.contactedAt||now_(),Notes:p.notes||'',Created_At:now_()};appendRows_('Contact_Attempts',[row]);audit_(u,'RECORD_CONTACT','Contact_Attempt',row.Contact_Attempt_ID,null,row,p.requestId);return row}
function interaction_(u,p){assertOwned_(u,p.affiliateId);var row={Interaction_ID:newId_('Interactions'),Affiliate_ID:p.affiliateId,Staff_ID:u.Staff_ID,Interaction_Type:p.type,Channel:p.channel,Summary:p.summary,Occurred_At:p.occurredAt||now_(),Created_At:now_()};appendRows_('Interactions',[row]);audit_(u,'LOG_INTERACTION','Interaction',row.Interaction_ID,null,row,p.requestId);return row}
function followup_(u,p){assertOwned_(u,p.affiliateId);var t=now_(),row={Followup_ID:newId_('Followups'),Affiliate_ID:p.affiliateId,Staff_ID:u.Staff_ID,Work_Item_ID:p.workItemId||'',Due_At:p.dueAt,Status:'PENDING',Reason:p.reason,Completed_At:'',Created_At:t,Updated_At:t};appendRows_('Followups',[row]);audit_(u,'CREATE_FOLLOWUP','Followup',row.Followup_ID,null,row,p.requestId);return row}
function completeWork_(u,p){var w=assertWork_(u,p.workItemId);var allowed=['COMPLETED','SKIPPED','CANCELLED'];if(allowed.indexOf(p.status)<0)throw apiError_('INVALID_STATUS','Invalid completion status.');if(p.status!=='COMPLETED'&&['SUPERVISOR','ADMIN','SUPER_ADMIN'].indexOf(u.Role)<0)throw apiError_('FORBIDDEN','Supervisor authorization required.');var before=updateById_('Work_Items','Work_Item_ID',w.Work_Item_ID,{Status:p.status,Outcome:p.outcome||'',Completed_At:now_(),Updated_At:now_()});audit_(u,'COMPLETE_WORK','Work_Item',w.Work_Item_ID,before,{Status:p.status,Outcome:p.outcome},p.requestId);return {workItemId:w.Work_Item_ID,status:p.status}}
function telegram_(u,p){var w=assertWork_(u,p.workItemId);var lock=LockService.getScriptLock();lock.waitLock(30000);try{contact_(u,{workItemId:w.Work_Item_ID,channel:'TELEGRAM',outcome:'TELEGRAM_CONNECTED',notes:p.notes||'',requestId:p.requestId});updateById_('Affiliates','Affiliate_ID',w.Affiliate_ID,{Lifecycle_Status:'TELEGRAM_CONNECTED',Updated_At:now_()});completeWork_(u,{workItemId:w.Work_Item_ID,status:'COMPLETED',outcome:'TELEGRAM_CONNECTED',requestId:p.requestId});audit_(u,'TELEGRAM_CONNECTED','Affiliate',w.Affiliate_ID,null,{replacementRequired:true},p.requestId);return {affiliateId:w.Affiliate_ID,status:'TELEGRAM_CONNECTED',replacementRequired:true}}finally{lock.releaseLock()}}

function normalize_(v){return String(v||'').trim().toLowerCase()}
function validateImport_(u,p){var existing=rows_('Affiliates'),byUser={},byPhone={};existing.forEach(function(a){byUser[normalize_(a.Username)]=a;if(a.Phone)byPhone[normalize_(a.Phone)]=a});var seen={};return (p.rows||[]).map(function(r,i){var user=normalize_(r.username),phone=normalize_(r.phone),found=byUser[user],status='NEW';if(!user||(!r.email&&!phone))status='MISSING_OR_INVALID_CONTACT';else if(seen[user])status='DUPLICATE_USERNAME_IN_BATCH';else if(found&&found.Lifecycle_Status==='ARCHIVED'&&(normalize_(found.Email)!==normalize_(r.email)||normalize_(found.Phone)!==phone))status='PREVIOUSLY_ARCHIVED_NEW_CONTACT';else if(found&&found.Lifecycle_Status==='ARCHIVED')status='PREVIOUSLY_ARCHIVED';else if(found)status='EXISTING_AFFILIATE';else if(phone&&byPhone[phone])status='EXISTING_PHONE';seen[user]=true;return {row:i+1,input:r,status:status,affiliateId:found&&found.Affiliate_ID||''}})}
function importAffiliates_(u,p){var validation=validateImport_(u,p),accepted=validation.filter(function(x){return x.status==='NEW'});if(accepted.length!==validation.length)throw apiError_('VALIDATION_FAILED','Import contains non-new or invalid rows. Resolve every result before commit.');var lock=LockService.getScriptLock();lock.waitLock(30000);try{var t=now_(),batchId=newId_('Import_Batches');var affiliates=accepted.map(function(x){return {Affiliate_ID:newId_('Affiliates'),Username:x.input.username,Email:x.input.email||'',Phone:x.input.phone||'',Brand_ID:p.brandId,Market:p.market||'',Lifecycle_Status:p.staffId?'ASSIGNED':'UNASSIGNED',Archive_Reason:'',Import_Batch_ID:batchId,Created_At:t,Updated_At:t,Archived_At:''}});appendRows_('Affiliates',affiliates);appendRows_('Import_Batches',[{Import_Batch_ID:batchId,File_Name:p.fileName||'pasted-data',Brand_ID:p.brandId,Assigned_Staff_ID:p.staffId||'',Market:p.market||'',Total_Rows:affiliates.length,New_Count:affiliates.length,Existing_Count:0,Rejected_Count:0,Status:'COMPLETED',Imported_By:u.Staff_ID,Created_At:t,Completed_At:t}]);if(p.staffId)assign_(u,{affiliateIds:affiliates.map(function(a){return a.Affiliate_ID}),staffId:p.staffId,requestId:p.requestId});audit_(u,'IMPORT_AFFILIATES','Import_Batch',batchId,null,{count:affiliates.length},p.requestId);return {importBatchId:batchId,created:affiliates.length}}finally{lock.releaseLock()}}
function assign_(u,p){var t=now_(),rows=(p.affiliateIds||[]).map(function(id){return {Assignment_ID:newId_('Assignments'),Affiliate_ID:id,Staff_ID:p.staffId,Assigned_By:u.Staff_ID,Assigned_At:t,Ended_At:'',End_Reason:'',Status:'ACTIVE'}});appendRows_('Assignments',rows);rows.forEach(function(a){updateById_('Affiliates','Affiliate_ID',a.Affiliate_ID,{Lifecycle_Status:'ASSIGNED',Updated_At:t})});audit_(u,'ASSIGN_AFFILIATES','Assignment','BATCH',null,{count:rows.length,staffId:p.staffId},p.requestId);return {assigned:rows.length}}
function transfer_(u,p){var lock=LockService.getScriptLock();lock.waitLock(30000);try{var active=rows_('Assignments').filter(function(a){return a.Affiliate_ID===p.affiliateId&&a.Status==='ACTIVE'})[0],t=now_();if(active)updateById_('Assignments','Assignment_ID',active.Assignment_ID,{Status:'ENDED',Ended_At:t,End_Reason:'TRANSFER'});return assign_(u,{affiliateIds:[p.affiliateId],staffId:p.staffId,requestId:p.requestId})}finally{lock.releaseLock()}}
function archive_(u,p){var before=updateById_('Affiliates','Affiliate_ID',p.affiliateId,{Lifecycle_Status:'ARCHIVED',Archive_Reason:p.reason,Archived_At:now_(),Updated_At:now_()});if(!before)throw apiError_('NOT_FOUND','Affiliate not found.');var active=rows_('Assignments').filter(function(a){return a.Affiliate_ID===p.affiliateId&&a.Status==='ACTIVE'})[0];if(active)updateById_('Assignments','Assignment_ID',active.Assignment_ID,{Status:'ENDED',Ended_At:now_(),End_Reason:p.reason});audit_(u,'ARCHIVE_AFFILIATE','Affiliate',p.affiliateId,before,{Lifecycle_Status:'ARCHIVED',reason:p.reason},p.requestId);return {affiliateId:p.affiliateId,status:'ARCHIVED',replacementRequired:true}}
function reopen_(u,p){var before=updateById_('Affiliates','Affiliate_ID',p.affiliateId,{Lifecycle_Status:'UNASSIGNED',Archive_Reason:'',Archived_At:'',Updated_At:now_()});if(!before)throw apiError_('NOT_FOUND','Affiliate not found.');audit_(u,'REOPEN_AFFILIATE','Affiliate',p.affiliateId,before,{Lifecycle_Status:'UNASSIGNED'},p.requestId);return {affiliateId:p.affiliateId,status:'UNASSIGNED'}}
