function staffDashboard_(u,p){
  requireRole_(u,['STAFF']);
  var work=myWork_(u,{page:1,pageSize:500}).items,followups=myFollowups_(u,{page:1,pageSize:500}).items,tasks=tasks_(u,{page:1,pageSize:500}).items,issues=issues_(u,{page:1,pageSize:500}).items,interactions=myInteractions_(u,{page:1,pageSize:500}).items,directory=affiliateDirectory_(u,{page:1,pageSize:500}),now=Date.now(),today=new Date(now),attention=[];
  function sameDay_(value){var d=value?new Date(value):null;return d&&!isNaN(d.getTime())&&d.getFullYear()===today.getFullYear()&&d.getMonth()===today.getMonth()&&d.getDate()===today.getDate()}
  work.forEach(function(x){if(x.overdue)attention.push({id:'WORK:'+x.workId,type:'WORK',title:x.title||x.workType,affiliateId:x.affiliateId,affiliateUsername:x.affiliateUsername,dueAt:x.dueAt,href:'/affiliates?workId='+encodeURIComponent(x.workId)})});
  followups.forEach(function(x){if(x.overdue)attention.push({id:'FOLLOWUP:'+x.followupId,type:'FOLLOWUP',title:x.followupType||'Follow-up',affiliateId:x.affiliateId,affiliateUsername:x.affiliateUsername,dueAt:x.dueAt,href:x.linkedWorkId?'/affiliates?workId='+encodeURIComponent(x.linkedWorkId):'/affiliates?affiliateId='+encodeURIComponent(x.affiliateId)})});
  tasks.forEach(function(x){if(x.overdue)attention.push({id:'TASK:'+x.taskId,type:'TASK',title:x.title,affiliateId:x.affiliateId,affiliateUsername:x.affiliateUsername,dueAt:x.dueAt,href:'/tasks'})});
  issues.forEach(function(x){if(x.priority==='URGENT'&&x.status!=='CLOSED')attention.push({id:'ISSUE:'+x.issueId,type:'ISSUE',title:x.title,affiliateId:x.affiliateId,affiliateUsername:x.affiliateUsername,dueAt:x.updatedAt,href:'/issues'})});
  attention.sort(function(a,b){return taskTime_(a.dueAt)-taskTime_(b.dueAt)});
  return {generatedAt:now_(),metrics:{openWork:work.length,overdueWork:work.filter(function(x){return x.overdue}).length,workDueToday:work.filter(function(x){return sameDay_(x.dueAt)}).length,openFollowups:followups.filter(function(x){return x.status!=='COMPLETED'}).length,followupsDueToday:followups.filter(function(x){return x.dueToday}).length,openTasks:tasks.filter(function(x){return TASK_OPEN_[x.status]}).length,overdueTasks:tasks.filter(function(x){return x.overdue}).length,openIssues:issues.filter(function(x){return x.status==='OPEN'||x.status==='IN_PROGRESS'}).length,urgentIssues:issues.filter(function(x){return x.priority==='URGENT'&&x.status!=='CLOSED'}).length,contactsToday:interactions.filter(function(x){return sameDay_(x.timestamp)}).length,telegramManaged:directory.items.filter(function(x){return x.telegramStatus==='CONNECTED'||x.lifecycleStatus==='TELEGRAM_CONNECTED'}).length},needsAttention:attention.slice(0,50)}
}
