function staffDashboard_(u,p){
  requireRole_(u,['STAFF']);
  var workResponse=myWork_(u,{page:1,pageSize:100}),followupResponse=myFollowups_(u,{page:1,pageSize:100}),taskResponse=tasks_(u,{page:1,pageSize:100}),issueResponse=issues_(u,{page:1,pageSize:100}),work=workResponse.items,followups=followupResponse.items,tasks=taskResponse.items,issues=issueResponse.items,directory=affiliateDirectory_(u,{page:1,pageSize:100}),now=Date.now(),today=new Date(now),contactsToday=interactionTodayCount_(u,now),performance=typeof performanceWorkspace_==='function'?performanceWorkspace_(u,{period:now_().slice(0,7)}):{summary:{notUpdated:0,needsAttention:0},items:[]},attention=[];
  function sameDay_(value){var d=value?new Date(value):null;return d&&!isNaN(d.getTime())&&d.getFullYear()===today.getFullYear()&&d.getMonth()===today.getMonth()&&d.getDate()===today.getDate()}
  work.forEach(function(x){if(x.overdue)attention.push({id:'WORK:'+x.workId,type:'WORK',title:x.title||x.workType,affiliateId:x.affiliateId,affiliateUsername:x.affiliateUsername,dueAt:x.dueAt,href:'/affiliates?workId='+encodeURIComponent(x.workId)})});
  followups.forEach(function(x){if(x.overdue)attention.push({id:'FOLLOWUP:'+x.followupId,type:'FOLLOWUP',title:x.followupType||'Follow-up',affiliateId:x.affiliateId,affiliateUsername:x.affiliateUsername,dueAt:x.dueAt,href:x.linkedWorkId?'/affiliates?workId='+encodeURIComponent(x.linkedWorkId):'/affiliates?affiliateId='+encodeURIComponent(x.affiliateId)})});
  tasks.forEach(function(x){if(x.overdue)attention.push({id:'TASK:'+x.taskId,type:'TASK',title:x.title,affiliateId:x.affiliateId,affiliateUsername:x.affiliateUsername,dueAt:x.dueAt,href:'/tasks'})});
  issues.forEach(function(x){if(x.priority==='URGENT'&&x.status!=='CLOSED')attention.push({id:'ISSUE:'+x.issueId,type:'ISSUE',title:x.title,affiliateId:x.affiliateId,affiliateUsername:x.affiliateUsername,dueAt:x.updatedAt,href:'/issues'})});
  performance.items.forEach(function(x){if(x.needsAttention)attention.push({id:'PERFORMANCE:'+x.affiliateId,type:'PERFORMANCE',title:x.attentionReasons.join(', '),affiliateId:x.affiliateId,affiliateUsername:x.affiliateUsername,dueAt:'',href:'/performance?affiliateId='+encodeURIComponent(x.affiliateId)})});
  attention.sort(function(a,b){return taskTime_(a.dueAt)-taskTime_(b.dueAt)});
  var workSummary=workResponse.summary||{open:work.length,overdue:work.filter(function(x){return x.overdue}).length,dueToday:work.filter(function(x){return sameDay_(x.dueAt)}).length},followupSummary=followupResponse.summary||{open:followups.filter(function(x){return x.status!=='COMPLETED'}).length,dueToday:followups.filter(function(x){return x.dueToday}).length},taskSummary=taskResponse.summary||{open:tasks.filter(function(x){return TASK_OPEN_[x.status]}).length,overdue:tasks.filter(function(x){return x.overdue}).length},issueSummary=issueResponse.summary||{open:issues.filter(function(x){return x.status==='OPEN'}).length,inProgress:issues.filter(function(x){return x.status==='IN_PROGRESS'}).length,urgent:issues.filter(function(x){return x.priority==='URGENT'&&x.status!=='CLOSED'}).length},directorySummary=directory.summary||{telegramConnected:directory.items.filter(function(x){return x.telegramStatus==='CONNECTED'||x.lifecycleStatus==='TELEGRAM_CONNECTED'}).length};
  return {generatedAt:now_(),metrics:{openWork:workSummary.open,overdueWork:workSummary.overdue,workDueToday:workSummary.dueToday,openFollowups:followupSummary.open,followupsDueToday:followupSummary.dueToday,openTasks:taskSummary.open,overdueTasks:taskSummary.overdue,openIssues:issueSummary.open+issueSummary.inProgress,urgentIssues:issueSummary.urgent,contactsToday:contactsToday,telegramManaged:directorySummary.telegramConnected,performanceNotUpdated:performance.summary.notUpdated,performanceNeedsAttention:performance.summary.needsAttention},needsAttention:attention.slice(0,50)}
}
