function teamAdmin_(user){return ['ADMIN','SUPER_ADMIN'].indexOf(String(user.Role))>=0}
function teamWorkspace_(user,p){
  p=p||{};var admin=teamAdmin_(user);if(!admin)requireRole_(user,['STAFF']);var period=performancePeriod_(p.period),staffRows=rows_('Staff_List'),teamRows=rows_('Team_List'),staffById={},teamById={};staffRows.forEach(function(row){staffById[performanceIdPart_(row.Staff_ID)]=row});teamRows.forEach(function(row){teamById[performanceIdPart_(row.Team_ID)]=row});var sessionStaff=staffById[performanceIdPart_(user.Staff_ID)]||null;if(!admin&&!sessionStaff)throw apiError_('FORBIDDEN','Staff profile is unavailable.');var authorizedTeam=admin?String(p.teamId||''):String(sessionStaff.Team||'');if(!admin&&!authorizedTeam)throw apiError_('FORBIDDEN','Staff team is unavailable.');
  var reportUser=admin?user:{Staff_ID:user.Staff_ID,Role:'ADMIN'},filters={period:period,teamId:authorizedTeam,staffId:admin?String(p.staffId||''):'',brandId:admin?String(p.brandId||''):''},report=reportsWorkspace_(reportUser,filters),scopedStaff={},memberRows=[];report.staff.forEach(function(row){scopedStaff[performanceIdPart_(row.staffId)]=row});staffRows.forEach(function(row){if(String(row.Status)!=='ACTIVE'||String(row.Role)!=='STAFF')return;if(authorizedTeam&&performanceIdPart_(row.Team)!==performanceIdPart_(authorizedTeam))return;if(admin&&p.staffId&&performanceIdPart_(row.Staff_ID)!==performanceIdPart_(p.staffId))return;var key=performanceIdPart_(row.Staff_ID);if(admin&&p.brandId&&!scopedStaff[key])return;var base=scopedStaff[key]||teamEmptyStaff_(row,teamById);scopedStaff[key]=base;memberRows.push(row)});
  var affiliateById={},assignmentByAffiliate={},assignmentIds={},telegramByStaff={},activityByStaff={},distributionByStaff={};rows_('Affiliates').forEach(function(row){affiliateById[performanceIdPart_(row.Affiliate_ID)]=row});rows_('Assignments').forEach(function(row){var staffKey=performanceIdPart_(row.Staff_ID),affiliateKey=performanceIdPart_(row.Affiliate_ID);if(String(row.Status)!=='ACTIVE'||!scopedStaff[staffKey])return;if(admin&&p.brandId&&performanceIdPart_(row.Brand_ID)!==performanceIdPart_(p.brandId))return;assignmentByAffiliate[affiliateKey]=row;assignmentIds[performanceIdPart_(row.Assignment_ID)]=true;var affiliate=affiliateById[affiliateKey]||{},stage=typeof dashboardPipeline_==='function'?dashboardPipeline_(affiliate):String(affiliate.Lifecycle_Status||'NEW_ASSIGNED'),dist=distributionByStaff[staffKey]||(distributionByStaff[staffKey]={});dist[stage]=(dist[stage]||0)+1;if(String(affiliate.Telegram_Status)==='CONNECTED'||String(affiliate.Lifecycle_Status)==='TELEGRAM_CONNECTED')telegramByStaff[staffKey]=(telegramByStaff[staffKey]||0)+1});
  var interactionWork={};rows_('Interactions').forEach(function(row){var assignmentId=performanceIdPart_(row.Assignment_ID),staffKey=performanceIdPart_(row.Staff_ID);if(!assignmentIds[assignmentId]||!scopedStaff[staffKey])return;if(row.Work_ID)interactionWork[String(row.Work_ID)]=true;if(performanceStoredPeriod_(row.Interaction_At||row.Created_At)===period)activityByStaff[staffKey]=(activityByStaff[staffKey]||0)+1});rows_('Contact_Attempts').forEach(function(row){var assignmentId=performanceIdPart_(row.Assignment_ID),staffKey=performanceIdPart_(row.Staff_ID);if(!assignmentIds[assignmentId]||!scopedStaff[staffKey]||row.Work_ID&&interactionWork[String(row.Work_ID)])return;if(performanceStoredPeriod_(row.Attempt_At||row.Created_At)===period)activityByStaff[staffKey]=(activityByStaff[staffKey]||0)+1});
  var staff=memberRows.map(function(row){var key=performanceIdPart_(row.Staff_ID),base=scopedStaff[key],managed=Number(base.assignedAffiliates)||0,updated=Number(base.updated)||0;return Object.assign({},base,{staffId:String(row.Staff_ID),staffName:String(row.Display_Name||''),role:String(row.Role),status:String(row.Status),teamId:String(row.Team||''),teamName:String((teamById[performanceIdPart_(row.Team)]||{}).Team_Name||''),telegramManaged:telegramByStaff[key]||0,performanceCompletion:managed?updated/managed*100:0,performanceDue:Number(base.updateDue)||0,activityCount:activityByStaff[key]||0,distribution:distributionByStaff[key]||{}})});staff.sort(function(a,b){return b.overdueWork-a.overdueWork||b.needsAttention-a.needsAttention||a.staffName.localeCompare(b.staffName)});
  var own=staff.filter(function(row){return performanceIdPart_(row.staffId)===performanceIdPart_(user.Staff_ID)})[0]||null,summary=Object.assign({},report.summary,{activeTeams:teamUniqueCount_(staff,'teamId'),activeStaff:staff.length,telegramManaged:staff.reduce(function(n,row){return n+row.telegramManaged},0),performanceDue:staff.reduce(function(n,row){return n+row.performanceDue},0)}),selected=admin&&p.staffId?staff.filter(function(row){return performanceIdPart_(row.staffId)===performanceIdPart_(p.staffId)})[0]||null:null,attention=[];if(selected)report.affiliates.filter(function(item){return performanceIdPart_(item.staffId)===performanceIdPart_(selected.staffId)&&item.needsAttention}).slice(0,20).forEach(function(item){attention.push({affiliateId:item.affiliateId,affiliateUsername:item.affiliateUsername,reason:item.attentionReasons.join(', '),href:'/performance?affiliateId='+encodeURIComponent(item.affiliateId)})});
  var team=authorizedTeam?teamById[performanceIdPart_(authorizedTeam)]||{}:{};return {period:period,canManage:admin,team:{teamId:String(team.Team_ID||''),teamName:String(team.Team_Name||''),teamCode:String(team.Team_Code||''),activeMembers:staff.length},summary:summary,ownSnapshot:admin?null:own,members:admin?staff:staff.map(teamSafeMember_),selectedStaff:selected?Object.assign({},selected,{attention:attention}):null,options:admin?report.options:{staff:[],teams:[],brands:[]}};
}
function teamEmptyStaff_(row,teams){return {staffId:String(row.Staff_ID),staffName:String(row.Display_Name||''),teamId:String(row.Team||''),teamName:String((teams[performanceIdPart_(row.Team)]||{}).Team_Name||''),assignedAffiliates:0,updated:0,updatedPercent:0,needsAttention:0,dataConflicts:0,updateDue:0,registeredUsers:0,ftd:0,activePlayers:0,totalDeposit:0,totalWithdrawal:0,totalTurnover:0,profitLoss:0,openWork:0,overdueWork:0,openFollowups:0,overdueFollowups:0,openTasks:0,overdueTasks:0,openIssues:0,ftdConversionRate:0,activePlayerRate:0}}
function teamSafeMember_(row){return {staffId:row.staffId,staffName:row.staffName,role:row.role,status:row.status,teamId:row.teamId,teamName:row.teamName,assignedAffiliates:row.assignedAffiliates,performanceCompletion:row.performanceCompletion,needsAttention:row.needsAttention,overdueWork:row.overdueWork}}
function teamUniqueCount_(rows,key){var seen={};rows.forEach(function(row){if(row[key])seen[row[key]]=true});return Object.keys(seen).length}
