'use client';
import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { api, ApiError, BrandRecord, CurrentUser, StaffRecord, TeamRecord } from '@/lib/api-client';
import styles from './admin.module.css';
type Tab='staff'|'teams'|'brands'|'import';
type Editor={kind:'staff';record?:StaffRecord}|{kind:'password';record:StaffRecord}|{kind:'team';record?:TeamRecord}|{kind:'brand';record?:BrandRecord};
const text=(data:FormData,key:string)=>String(data.get(key)||'').trim(); const number=(data:FormData,key:string)=>Number(data.get(key)||0);

export default function AdminPage(){
  const [user,setUser]=useState<CurrentUser|null>(null),[checking,setChecking]=useState(true),[tab,setTab]=useState<Tab>('staff');
  const [staff,setStaff]=useState<StaffRecord[]>([]),[teams,setTeams]=useState<TeamRecord[]>([]),[brands,setBrands]=useState<BrandRecord[]>([]);
  const [loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[editor,setEditor]=useState<Editor|null>(null);
  const authorized=user?.role==='ADMIN'||user?.role==='SUPER_ADMIN',root=user?.role==='SUPER_ADMIN';
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [s,t,b]=await Promise.all([api.listStaff(),api.listTeams(),api.listBrands()]);setStaff(s);setTeams(t);setBrands(b)}catch(cause){setError(message_(cause))}finally{setLoading(false)}},[]);
  useEffect(()=>{try{const saved=localStorage.getItem('crm_user');const parsed=saved?JSON.parse(saved) as CurrentUser:null;setUser(parsed);if(parsed?.role==='ADMIN'||parsed?.role==='SUPER_ADMIN')void load()}catch{setUser(null)}finally{setChecking(false)}},[load]);
  async function mutate(action:()=>Promise<unknown>,message:string){if(busy)return;setBusy(true);setError('');setSuccess('');try{await action();setEditor(null);setSuccess(message);await load()}catch(cause){setError(message_(cause))}finally{setBusy(false)}}
  if(checking)return <AdminState title="Checking access…"/>; if(!authorized)return <AdminState title="Access denied" detail="This workspace is available only to authorized administrators."/>;
  return <><div className={styles.heading}><div><h1>Admin</h1><p className="muted">Manage access and operational catalogs using live CRM records.</p></div>{loading&&<span className={styles.loading}>Refreshing…</span>}</div>
    {error&&<div className={styles.error}>{error}</div>}{success&&<div className={styles.success}>{success}</div>}
    <div className={styles.tabs}>{([['staff','Staff & Access'],['teams','Teams'],['brands','Brands'],['import','Bulk Affiliate Import']] as [Tab,string][]).map(([key,label])=><button className={tab===key?styles.activeTab:''} onClick={()=>setTab(key)} key={key}>{label}</button>)}</div>
    {tab==='staff'&&<StaffSection records={staff} teams={teams} canManage={root} busy={busy} onCreate={()=>setEditor({kind:'staff'})} onEdit={(record)=>setEditor({kind:'staff',record})} onPassword={(record)=>setEditor({kind:'password',record})} onStatus={(record,status)=>void mutate(()=>api.setStaffStatus(record.staffId,status),`${record.displayName||record.username} is now ${status.toLowerCase()}.`)}/>}
    {tab==='teams'&&<TeamSection records={teams} canManage={root} onCreate={()=>setEditor({kind:'team'})} onEdit={(record)=>setEditor({kind:'team',record})}/>}
    {tab==='brands'&&<BrandSection records={brands} onCreate={()=>setEditor({kind:'brand'})} onEdit={(record)=>setEditor({kind:'brand',record})}/>}
    {tab==='import'&&<section className="card empty-state"><div><div className="empty-icon">⇧</div><h2>Bulk Affiliate Import</h2><p className="muted">Validate pasted prospects, then assign them directly to active staff or add them to the unassigned pool.</p><Link className="primary" href="/admin/import">Open importer →</Link></div></section>}
    {editor&&<EditorModal editor={editor} teams={teams} busy={busy} onClose={()=>!busy&&setEditor(null)} onSubmit={(event)=>void submitEditor_(event,editor,mutate)}/>}
  </>;
}

function StaffSection({records,teams,canManage,busy,onCreate,onEdit,onPassword,onStatus}:{records:StaffRecord[];teams:TeamRecord[];canManage:boolean;busy:boolean;onCreate:()=>void;onEdit:(r:StaffRecord)=>void;onPassword:(r:StaffRecord)=>void;onStatus:(r:StaffRecord,s:StaffRecord['status'])=>void}){const teamName=(id:string)=>teams.find((t)=>t.teamId===id)?.teamName||id||'—';return <section className="card"><div className="section-head"><div><h2>Staff & Access</h2><p className="muted">{records.length} staff account{records.length===1?'':'s'}</p></div>{canManage&&<button className="primary" onClick={onCreate}>Create Staff</button>}</div><div className={styles.tableWrap}><table className="table"><thead><tr><th>Display Name</th><th>Username</th><th>Role</th><th>Team</th><th>Status</th><th>Prospect Target</th><th>Max Managed</th><th>Created</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{records.map((r)=><tr key={r.staffId}><td>{r.displayName||'—'}</td><td>{r.username}</td><td>{r.role}</td><td>{teamName(r.team)}</td><td><Status value={r.status}/></td><td>{r.prospectTarget??'—'}</td><td>{r.maxManagedAffiliates??'—'}</td><td>{date_(r.createdAt)}</td>{canManage&&<td><div className={styles.actions}><button onClick={()=>onEdit(r)}>Edit</button><button onClick={()=>onPassword(r)}>Reset password</button>{r.status!=='ACTIVE'&&<button disabled={busy} onClick={()=>onStatus(r,'ACTIVE')}>Activate</button>}{r.status!=='SUSPENDED'&&<button disabled={busy} onClick={()=>onStatus(r,'SUSPENDED')}>Suspend</button>}{r.status!=='INACTIVE'&&<button disabled={busy} onClick={()=>onStatus(r,'INACTIVE')}>Set inactive</button>}</div></td>}</tr>)}</tbody></table></div>{!records.length&&<Empty text="No staff records found."/>}</section>}
function TeamSection({records,canManage,onCreate,onEdit}:{records:TeamRecord[];canManage:boolean;onCreate:()=>void;onEdit:(r:TeamRecord)=>void}){return <section className="card"><div className="section-head"><div><h2>Teams</h2><p className="muted">Stable team IDs and default portfolio limits.</p></div>{canManage&&<button className="primary" onClick={onCreate}>Create Team</button>}</div><div className={styles.cards}>{records.map((r)=><article className={styles.catalog} key={r.teamId}><div><Status value={r.status}/><h3>{r.teamName}</h3><code>{r.teamCode}</code></div><dl><div><dt>Prospect target</dt><dd>{r.defaultProspectTarget}</dd></div><div><dt>Max managed</dt><dd>{r.defaultMaxManagedAffiliates}</dd></div></dl>{canManage&&<button onClick={()=>onEdit(r)}>Edit team</button>}</article>)}</div>{!records.length&&<Empty text="No teams configured."/>}</section>}
function BrandSection({records,onCreate,onEdit}:{records:BrandRecord[];onCreate:()=>void;onEdit:(r:BrandRecord)=>void}){return <section className="card"><div className="section-head"><div><h2>Brands</h2><p className="muted">Operational brand catalog.</p></div><button className="primary" onClick={onCreate}>Create Brand</button></div><div className={styles.cards}>{records.map((r)=><article className={styles.catalog} key={r.brandId}><div><Status value={r.status}/><h3>{r.brandName}</h3><code>{r.brandCode}</code></div><dl><div><dt>Market</dt><dd>{r.market}</dd></div><div><dt>Language</dt><dd>{r.defaultLanguage}</dd></div><div><dt>Sort</dt><dd>{r.sortOrder}</dd></div></dl><button onClick={()=>onEdit(r)}>Edit brand</button></article>)}</div>{!records.length&&<Empty text="No brands configured."/>}</section>}

function EditorModal({editor,teams,busy,onClose,onSubmit}:{editor:Editor;teams:TeamRecord[];busy:boolean;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className={styles.overlay} role="presentation" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><section className={styles.modal} role="dialog" aria-modal="true"><div className="section-head"><h2>{title_(editor)}</h2><button onClick={onClose} aria-label="Close">×</button></div><form className={styles.form} onSubmit={onSubmit}>{editor.kind==='staff'&&<StaffFields record={editor.record} teams={teams}/>} {editor.kind==='password'&&<><p className="muted">Reset password for {editor.record?.displayName||editor.record?.username}. Every active session will be revoked.</p><label>New password<input name="newPassword" type="password" minLength={12} required autoComplete="new-password"/></label></>} {editor.kind==='team'&&<TeamFields record={editor.record}/>} {editor.kind==='brand'&&<BrandFields record={editor.record}/>}<div className={styles.formActions}><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save'}</button></div></form></section></div>}
function StaffFields({record,teams}:{record?:StaffRecord;teams:TeamRecord[]}){const root=record?.role==='SUPER_ADMIN';return <><div className={styles.two}><label>Display Name<input name="displayName" defaultValue={record?.displayName} required/></label>{!record&&<label>Username<input name="username" required autoComplete="off"/></label>}</div><label>Email<input name="email" type="email" defaultValue={record?.email} required/></label>{root?<><input name="team" type="hidden" value={record.team}/><input name="role" type="hidden" value="SUPER_ADMIN"/></>:<div className={styles.two}><label>Team<select name="team" defaultValue={record?.team} required><option value="">Select team</option>{teams.filter((t)=>t.status==='ACTIVE'||t.teamId===record?.team).map((t)=><option value={t.teamId} key={t.teamId}>{t.teamName} ({t.teamCode})</option>)}</select></label><label>Role<select name="role" defaultValue={record?.role||'STAFF'}><option>STAFF</option><option>SUPERVISOR</option><option>ADMIN</option></select></label></div>}<div className={styles.two}><label>Prospect Target<input name="prospectTarget" type="number" min="0" defaultValue={record?.prospectTarget}/></label><label>Max Managed Affiliates<input name="maxManagedAffiliates" type="number" min="0" defaultValue={record?.maxManagedAffiliates}/></label></div>{!record&&<><label>Initial Password<input name="password" type="password" minLength={12} required autoComplete="new-password"/></label><label>Status<select name="status" defaultValue="ACTIVE"><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select></label></>}</>}
function TeamFields({record}:{record?:TeamRecord}){return <><div className={styles.two}><label>Team Name<input name="teamName" defaultValue={record?.teamName} required/></label><label>Team Code<input name="teamCode" defaultValue={record?.teamCode} required/></label></div><div className={styles.two}><label>Default Prospect Target<input name="defaultProspectTarget" type="number" min="0" defaultValue={record?.defaultProspectTarget||0}/></label><label>Default Max Managed Affiliates<input name="defaultMaxManagedAffiliates" type="number" min="0" defaultValue={record?.defaultMaxManagedAffiliates||0}/></label></div><label>Status<select name="status" defaultValue={record?.status||'ACTIVE'}><option>ACTIVE</option><option>INACTIVE</option></select></label></>}
function BrandFields({record}:{record?:BrandRecord}){return <><div className={styles.two}><label>Brand Name<input name="brandName" defaultValue={record?.brandName} required/></label><label>Brand Code<input name="brandCode" defaultValue={record?.brandCode} required/></label></div><div className={styles.two}><label>Market<input name="market" defaultValue={record?.market} required/></label><label>Default Language<input name="defaultLanguage" defaultValue={record?.defaultLanguage} required/></label></div><div className={styles.two}><label>Sort Order<input name="sortOrder" type="number" min="0" defaultValue={record?.sortOrder||0}/></label><label>Status<select name="status" defaultValue={record?.status||'ACTIVE'}><option>ACTIVE</option><option>INACTIVE</option></select></label></div></>}

async function submitEditor_(event:FormEvent<HTMLFormElement>,editor:Editor,mutate:(action:()=>Promise<unknown>,message:string)=>Promise<void>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);if(editor.kind==='password'){const password=text(data,'newPassword');await mutate(()=>api.resetStaffPassword(editor.record!.staffId,password),'Password reset and active sessions revoked.');form.reset();return}if(editor.kind==='staff'){const payload={staffId:editor.record?.staffId,displayName:text(data,'displayName'),username:text(data,'username'),email:text(data,'email'),team:text(data,'team'),role:text(data,'role'),prospectTarget:number(data,'prospectTarget'),maxManagedAffiliates:number(data,'maxManagedAffiliates'),password:text(data,'password'),status:text(data,'status')};await mutate(()=>editor.record?api.updateStaff(payload):api.createStaff(payload),editor.record?'Staff record updated.':'Staff account created.');form.reset();return}if(editor.kind==='team'){const payload={teamId:editor.record?.teamId,teamName:text(data,'teamName'),teamCode:text(data,'teamCode'),defaultProspectTarget:number(data,'defaultProspectTarget'),defaultMaxManagedAffiliates:number(data,'defaultMaxManagedAffiliates'),status:text(data,'status')};await mutate(()=>editor.record?api.updateTeam(payload):api.createTeam(payload),editor.record?'Team updated.':'Team created.');return}const payload={brandId:editor.record?.brandId,brandName:text(data,'brandName'),brandCode:text(data,'brandCode'),market:text(data,'market'),defaultLanguage:text(data,'defaultLanguage'),sortOrder:number(data,'sortOrder'),status:text(data,'status')};await mutate(()=>editor.record?api.updateBrand(payload):api.createBrand(payload),editor.record?'Brand updated.':'Brand created.')}
function Status({value}:{value:string}){return <span className={`${styles.status} ${value==='ACTIVE'?styles.on:styles.off}`}>{value}</span>} function Empty({text}:{text:string}){return <div className={styles.inlineEmpty}>{text}</div>}
function AdminState({title,detail}:{title:string;detail?:string}){return <section className="card empty-state"><div><div className="empty-icon">⚙</div><h2>{title}</h2>{detail&&<p className="muted">{detail}</p>}</div></section>}
function title_(editor:Editor){if(editor.kind==='password')return'Reset password';if(editor.kind==='staff')return editor.record?'Edit staff':'Create staff';if(editor.kind==='team')return editor.record?'Edit team':'Create team';return editor.record?'Edit brand':'Create brand'} function message_(cause:unknown){return cause instanceof ApiError?cause.message:'The admin request could not be completed.'} function date_(value:string){if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleDateString()}
