const assert=require('assert'),fs=require('fs'),vm=require('vm');
function env(){const data={Affiliates:[{Affiliate_ID:'A1',Affiliate_Username:'fixed.user',Affiliate_Name:'Old Name',Email:'old@example.com',Phone:'+94111',Telegram_Username:'@old_user',Preferred_Channel:'CALL',Brand_ID:'B1',Lifecycle_Status:'ASSIGNED'}],Assignments:[{Assignment_ID:'AS1',Affiliate_ID:'A1',Staff_ID:'S1',Status:'ACTIVE'}]},audits=[];const c={console,Date,String,Number,Math,Object,isFinite,PROSPECT_CHANNELS_:['CALL','WHATSAPP','TELEGRAM','EMAIL','OTHER'],apiError_:(code,message)=>Object.assign(new Error(message),{code}),requireRole_:(u,roles)=>{if(!roles.includes(u.Role))throw c.apiError_('FORBIDDEN','Denied')},rows_:n=>data[n]||[],clearCache_:()=>{},safeSheetText_:(v,max)=>String(v||'').trim().slice(0,max),now_:()=>new Date().toISOString(),LockService:{getScriptLock:()=>({waitLock:()=>{},releaseLock:()=>{}})},updateById_:(n,k,id,ch)=>{const row=data[n].find(x=>x[k]===id),before={...row};Object.assign(row,ch);return before},audit_:(u,action,type,id,affiliateId,before,after)=>audits.push({u,action,type,id,affiliateId,before,after})};vm.createContext(c);vm.runInContext(fs.readFileSync('backend/Directory.gs','utf8'),c);return{c,data,audits}}
const owner={Staff_ID:'S1',Role:'STAFF'},other={Staff_ID:'S2',Role:'STAFF'},base={affiliateId:'A1',affiliateName:'New Name',email:'new@example.com',phone:'+94 77 123 4567',telegramUsername:'@new_user',preferredChannel:'WHATSAPP'};
{const{c,data,audits}=env(),r=c.updateAffiliateDetails_(owner,base);assert.equal(r.affiliateId,'A1');assert.equal(r.affiliateUsername,'fixed.user');assert.equal(data.Affiliates[0].Affiliate_Name,'New Name');assert.equal(data.Affiliates[0].Email,'new@example.com');assert.equal(data.Affiliates[0].Phone,'+94 77 123 4567');assert.equal(data.Affiliates[0].Brand_ID,'B1');assert.equal(data.Assignments[0].Staff_ID,'S1');assert.equal(audits.length,1);assert.equal(audits[0].action,'AFFILIATE_DETAILS_UPDATED');assert.deepEqual(Array.from(audits[0].after.fields).sort(),['Affiliate_Name','Email','Phone','Preferred_Channel','Telegram_Username'].sort());assert.equal(audits[0].before.values.Email,'old@example.com');assert.equal(audits[0].after.values.Email,'new@example.com');assert.ok(!JSON.stringify({r,audits}).match(/Password_Hash|Session_Token_Hash|password|token/i))}
{const{c}=env();assert.throws(()=>c.updateAffiliateDetails_(other,{...base,staffId:'S1'}),e=>e.code==='FORBIDDEN')}
for(const injected of [{Affiliate_ID:'HACK'},{affiliateUsername:'hacked'},{brandId:'B2'},{assignmentId:'OTHER'},{staffId:'S1'},{Lifecycle_Status:'CONNECTED'}]){const{c,data,audits}=env();assert.throws(()=>c.updateAffiliateDetails_(owner,{...base,...injected}),e=>e.code==='VALIDATION_FAILED');assert.equal(data.Affiliates[0].Affiliate_ID,'A1');assert.equal(data.Affiliates[0].Affiliate_Username,'fixed.user');assert.equal(data.Affiliates[0].Brand_ID,'B1');assert.equal(audits.length,0)}
{const{c}=env();assert.throws(()=>c.updateAffiliateDetails_(owner,{...base,email:'bad-email'}),e=>e.code==='VALIDATION_FAILED');assert.throws(()=>c.updateAffiliateDetails_(owner,{...base,preferredChannel:'SMS'}),e=>e.code==='VALIDATION_FAILED')}
{const{c,audits}=env();assert.throws(()=>c.updateAffiliateDetails_(owner,{affiliateId:'A1',affiliateName:'Old Name',email:'old@example.com',phone:'+94111',telegramUsername:'@old_user',preferredChannel:'CALL'}),e=>e.code==='INVALID_STATE');assert.equal(audits.length,0)}
const api=fs.readFileSync('backend/Api.gs','utf8'),page=fs.readFileSync('app/affiliates/update-details/page.tsx','utf8'),affiliatePage=fs.readFileSync('app/affiliates/page.tsx','utf8');assert.match(api,/sessionUser_\(request\.token\).*updateAffiliateDetails/s);assert.match(page,/api\.updateAffiliateDetails/);assert.match(affiliatePage,/update-details\?affiliateId=/);console.log('affiliate update tests passed');
