const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function environment(){const data={Work_Items:[{Work_ID:'FIRST1',Affiliate_ID:'AFF1',Assignment_ID:'ASN1',Staff_ID:'STF1',Work_Type:'FIRST_CONTACT',Status:'COMPLETED'},{Work_ID:'CALL1',Affiliate_ID:'AFF1',Assignment_ID:'ASN1',Staff_ID:'STF1',Work_Type:'CALLBACK',Work_Channel:'CALL',Priority:'NORMAL',Status:'PENDING',Title:'Affiliate callback',Reason:'CALLBACK_REQUESTED',Assigned_At:'2026-01-01T00:00:00.000Z',Due_At:'2026-01-02T00:00:00.000Z',Started_At:'',Completed_At:'',Outcome:'',Completion_Notes:'',Next_Action_At:'',Parent_Work_ID:'FIRST1'}],Assignments:[{Assignment_ID:'ASN1',Affiliate_ID:'AFF1',Staff_ID:'STF1',Brand_ID:'BRD1',Status:'ACTIVE'}],Affiliates:[{Affiliate_ID:'AFF1',Affiliate_Username:'callback.user',Affiliate_Name:'Callback User',Email:'callback@example.com',Phone:'123',Telegram_Username:'',Telegram_Status:'NOT_CONNECTED',Lifecycle_Status:'CALLBACK',Prospect_Status:'ACTIVE',Brand_ID:'BRD1'}],Brand_List:[{Brand_ID:'BRD1',Brand_Name:'Alpha'}],Staff_List:[{Staff_ID:'STF1',Display_Name:'Owner'}],Contact_Attempts:[],Interactions:[],Followups:[{Followup_ID:'FUP1',Affiliate_ID:'AFF1',Assignment_ID:'ASN1',Staff_ID:'STF1',Source_Work_ID:'FIRST1',Followup_Type:'CALLBACK',Status:'PENDING',Due_At:'2026-01-02T00:00:00.000Z'}],Audit_Log:[]},counters={};const context={console,Date,String,Number,Boolean,Array,Math,JSON,isFinite,apiError_:(code,message)=>Object.assign(new Error(message),{code}),rows_:name=>data[name],clearCache_:()=>{},now_:()=>new Date().toISOString(),config_:()=>24,LockService:{getScriptLock:()=>({waitLock:()=>{},releaseLock:()=>{}})},reserveIdsUnlocked_:(entity,count)=>Array.from({length:count},()=>{counters[entity]=(counters[entity]||0)+1;return ({Attempt:'ATM',Interaction:'INT',Work:'WRK',Followup:'FUP'}[entity])+String(counters[entity]).padStart(6,'0')}),appendRows_:(name,rows)=>data[name].push(...rows.map(x=>({...x}))),updateById_:(name,column,id,changes)=>{const found=data[name].find(x=>String(x[column])===String(id));if(!found)return null;const before={...found};Object.assign(found,changes);return before},audit_:(u,action,type,id,affiliateId,before,after)=>data.Audit_Log.push({action,id,affiliateId,after})};vm.createContext(context);vm.runInContext(fs.readFileSync('backend/Workflow.gs','utf8'),context);return {context,data}}
const owner={Staff_ID:'STF1',Role:'STAFF'},other={Staff_ID:'STF2',Role:'STAFF'};
{const {context}=environment();assert.equal(context.workWorkspace_(owner,{workId:'CALL1'}).work.workType,'CALLBACK');assert.throws(()=>context.workWorkspace_(other,{workId:'CALL1'}),e=>e.code==='FORBIDDEN')}
{const {context,data}=environment();context.submitCallbackOutcome_(owner,{workId:'CALL1',outcome:'CONNECTED',telegramStatus:'TELEGRAM_CONNECTED',telegramUsername:'@callback'});assert.equal(data.Work_Items[1].Status,'COMPLETED');assert.equal(data.Followups[0].Status,'COMPLETED');assert.equal(data.Contact_Attempts.length,1);assert.equal(data.Interactions.length,1);assert.equal(data.Affiliates[0].Telegram_Status,'CONNECTED');assert.throws(()=>context.submitCallbackOutcome_(owner,{workId:'CALL1',outcome:'NO_ANSWER'}),e=>e.code==='INVALID_STATE');assert.equal(data.Contact_Attempts.length,1)}
{const {context,data}=environment();data.Contact_Attempts.push({Attempt_ID:'OLD',Affiliate_ID:'AFF1',Assignment_ID:'ASN1',Work_ID:'FIRST1'});context.submitCallbackOutcome_(owner,{workId:'CALL1',outcome:'NO_ANSWER'});assert.equal(data.Contact_Attempts.length,2);assert.equal(data.Interactions.length,0);assert.equal(data.Work_Items.filter(x=>x.Work_Type==='CALLBACK'&&x.Parent_Work_ID==='CALL1').length,1);assert.equal(data.Followups.filter(x=>x.Status==='PENDING').length,1);assert.equal(data.Followups[0].Status,'COMPLETED')}
{const {context,data}=environment(),future=new Date(Date.now()+3600000).toISOString();assert.throws(()=>context.submitCallbackOutcome_(owner,{workId:'CALL1',outcome:'CALLBACK_REQUESTED',callbackAt:new Date(Date.now()-1000).toISOString()}),/future callback/);context.submitCallbackOutcome_(owner,{workId:'CALL1',outcome:'CALLBACK_REQUESTED',callbackAt:future,notes:'Call again'});assert.equal(data.Work_Items.filter(x=>x.Parent_Work_ID==='CALL1').length,1);assert.equal(data.Followups.filter(x=>x.Source_Work_ID===data.Work_Items[2].Work_ID).length,1);assert.equal(data.Followups.length,2)}
{for(const outcome of ['WRONG_OR_INVALID_CONTACT','OTHER']){const {context}=environment();assert.throws(()=>context.submitCallbackOutcome_(owner,{workId:'CALL1',outcome}),/note is required/)}}
{const {context,data}=environment();context.submitCallbackOutcome_(owner,{workId:'CALL1',outcome:'WRONG_OR_INVALID_CONTACT',notes:'Number belongs to someone else'});assert.equal(data.Followups[0].Status,'COMPLETED');assert.equal(data.Contact_Attempts.length,1);assert.equal(data.Interactions.length,0);assert.equal(data.Affiliates.length,1)}
{const {context,data}=environment();context.submitCallbackOutcome_(owner,{workId:'CALL1',outcome:'OTHER',notes:'=IMPORTXML("bad")'});assert.equal(data.Contact_Attempts[0].Notes.startsWith("'="),true);assert.equal(data.Interactions[0].Notes.startsWith("'="),true);assert.ok(!JSON.stringify(data.Audit_Log).match(/IMPORTXML|callback@example|123/))}
{const {context,data}=environment();assert.throws(()=>context.submitCallbackOutcome_(other,{workId:'CALL1',outcome:'NO_ANSWER',staffId:'STF1'}),e=>e.code==='FORBIDDEN');assert.equal(data.Contact_Attempts.length,0);assert.equal(data.Followups.length,1)}
console.log('Callback execution, history, validation, ownership, and idempotency scenarios passed');
