const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function environment(options={}){const data={Work_Items:[{Work_ID:'WRK000001',Affiliate_ID:'AFF000001',Assignment_ID:'ASN000001',Staff_ID:'STF000004',Work_Type:'FIRST_CONTACT',Work_Channel:'CALL',Priority:'NORMAL',Status:'PENDING',Title:'Initial affiliate contact',Reason:'NEW_PROSPECT',Assigned_At:'2026-01-01T00:00:00.000Z',Due_At:'2026-01-02T00:00:00.000Z',Started_At:'',Completed_At:'',Outcome:'',Completion_Notes:'',Next_Action_At:'',Parent_Work_ID:''}],Assignments:[{Assignment_ID:'ASN000001',Affiliate_ID:'AFF000001',Staff_ID:'STF000004',Brand_ID:'BRD000001',Status:options.inactive?'ENDED':'ACTIVE'}],Affiliates:options.orphan?[]:[{Affiliate_ID:'AFF000001',Affiliate_Username:'prospect1',Affiliate_Name:'Prospect One',Email:'p@example.com',Phone:'+94770000000',Telegram_Username:'',Preferred_Channel:'CALL',Telegram_Status:'NOT_CONNECTED',Lifecycle_Status:'ASSIGNED',Prospect_Status:'NEW',Brand_ID:'BRD000001'}],Brand_List:[{Brand_ID:'BRD000001',Brand_Name:'Alpha',Brand_Code:'ALPHA'}],Staff_List:[{Staff_ID:'STF000004',Display_Name:'Test Staff'}],Contact_Attempts:[],Interactions:[],Followups:[],Audit_Log:[]},counters={};const context={console,Date,String,Number,Boolean,Array,Math,JSON,isFinite,apiError_:(code,message)=>Object.assign(new Error(message),{code}),rows_:name=>data[name],clearCache_:()=>{},now_:()=>new Date().toISOString(),config_:key=>key==='CALL_RETRY_HOURS'?24:24,LockService:{getScriptLock:()=>({waitLock:()=>{},releaseLock:()=>{}})},reserveIdsUnlocked_:(entity,count)=>Array.from({length:count},()=>{counters[entity]=(counters[entity]||0)+1;return ({Attempt:'ATM',Interaction:'INT',Work:'WRK',Followup:'FUP'}[entity])+String(counters[entity]).padStart(6,'0')}),appendRows_:(name,rows)=>data[name].push(...rows.map(x=>({...x}))),updateById_:(name,column,id,changes)=>{const found=data[name].find(x=>String(x[column])===String(id));if(!found)return null;const before={...found};Object.assign(found,changes);return before},audit_:(u,action,type,id,affiliateId,before,after)=>data.Audit_Log.push({action,id,affiliateId,after})};vm.createContext(context);vm.runInContext(fs.readFileSync('backend/Workflow.gs','utf8'),context);return {context,data}}
const owner={Staff_ID:'STF000004',Role:'STAFF'},other={Staff_ID:'STF000005',Role:'STAFF'};
{const {context}=environment();const view=context.workWorkspace_(owner,{workId:'WRK000001',staffId:'STF999999'});assert.equal(view.affiliate.affiliateUsername,'prospect1');assert.equal(view.brand.brandName,'Alpha');assert.throws(()=>context.workWorkspace_(other,{workId:'WRK000001'}),e=>e.code==='FORBIDDEN')}
{assert.throws(()=>environment({inactive:true}).context.workWorkspace_(owner,{workId:'WRK000001'}),e=>e.code==='INVALID_STATE');assert.throws(()=>environment({orphan:true}).context.workWorkspace_(owner,{workId:'WRK000001'}),e=>e.code==='NOT_FOUND')}
{const {context,data}=environment();const result=context.submitFirstContactOutcome_(owner,{workId:'WRK000001',outcome:'CONNECTED',telegramStatus:'TELEGRAM_NOT_CONNECTED',notes:'Spoke successfully'});assert.equal(data.Work_Items[0].Status,'COMPLETED');assert.equal(data.Affiliates[0].Lifecycle_Status,'CONNECTED');assert.equal(data.Contact_Attempts.length,1);assert.equal(data.Interactions.length,1);assert.ok(result.nextWorkId);assert.equal(data.Work_Items[1].Work_Type,'TELEGRAM_ONBOARDING');assert.equal(data.Work_Items[1].Work_Channel,'TELEGRAM');assert.throws(()=>context.submitFirstContactOutcome_(owner,{workId:'WRK000001',outcome:'CONNECTED',telegramStatus:'TELEGRAM_NOT_CONNECTED'}),e=>e.code==='INVALID_STATE');assert.equal(data.Contact_Attempts.length,1)}
{const {context,data}=environment();context.submitFirstContactOutcome_(owner,{workId:'WRK000001',outcome:'CONNECTED',telegramStatus:'TELEGRAM_CONNECTED',telegramUsername:'@prospect'});assert.equal(data.Affiliates[0].Telegram_Status,'CONNECTED');assert.equal(data.Affiliates[0].Telegram_Username,"'@prospect");assert.equal(data.Affiliates[0].Lifecycle_Status,'TELEGRAM_CONNECTED');assert.equal(data.Work_Items.length,1)}
{const {context,data}=environment();context.submitFirstContactOutcome_(owner,{workId:'WRK000001',outcome:'NO_ANSWER'});assert.equal(data.Contact_Attempts.length,1);assert.equal(data.Interactions.length,0);assert.equal(data.Work_Items.length,2);assert.equal(data.Work_Items[1].Work_Type,'FIRST_CONTACT');assert.equal(data.Work_Items[1].Work_Channel,'CALL');assert.equal(data.Affiliates[0].Lifecycle_Status,'RETRY')}
{const {context,data}=environment(),future=new Date(Date.now()+3600000).toISOString();assert.throws(()=>context.submitFirstContactOutcome_(owner,{workId:'WRK000001',outcome:'CALLBACK_REQUESTED',callbackAt:new Date(Date.now()-1000).toISOString()}),/future callback/);const result=context.submitFirstContactOutcome_(owner,{workId:'WRK000001',outcome:'CALLBACK_REQUESTED',callbackAt:future,notes:'Call later'});assert.equal(data.Work_Items.filter(x=>x.Parent_Work_ID==='WRK000001').length,1);assert.equal(data.Followups.length,1);assert.equal(data.Interactions.length,1);assert.ok(result.followupId)}
{const {context}=environment();assert.throws(()=>context.submitFirstContactOutcome_(owner,{workId:'WRK000001',outcome:'WRONG_OR_INVALID_CONTACT'}),/note is required/);assert.throws(()=>context.submitFirstContactOutcome_(owner,{workId:'WRK000001',outcome:'OTHER'}),/note is required/)}
{const {context,data}=environment();context.submitFirstContactOutcome_(owner,{workId:'WRK000001',outcome:'WRONG_OR_INVALID_CONTACT',notes:'Number reaches another person'});assert.equal(data.Contact_Attempts.length,1);assert.equal(data.Interactions.length,0);assert.equal(data.Affiliates[0].Lifecycle_Status,'CONTACTING');assert.equal(data.Affiliates[0].Prospect_Status,'ACTIVE')}
{const {context,data}=environment();context.submitFirstContactOutcome_(owner,{workId:'WRK000001',outcome:'OTHER',notes:'=IMPORTXML("bad")'});assert.equal(data.Contact_Attempts[0].Notes.startsWith("'="),true);assert.equal(data.Interactions.length,1);assert.equal(data.Audit_Log[0].after.Notes,undefined);assert.ok(!JSON.stringify(data.Audit_Log).match(/p@example|947700|IMPORTXML/))}
{const {context,data}=environment();assert.throws(()=>context.submitFirstContactOutcome_(other,{workId:'WRK000001',outcome:'NO_ANSWER',staffId:'STF000004'}),e=>e.code==='FORBIDDEN');assert.equal(data.Contact_Attempts.length,0)}
{const {context,data}=environment();data.Contact_Attempts.push({Attempt_ID:'ATM999999',Affiliate_ID:'AFF000001',Assignment_ID:'ASN000001',Work_ID:'WRK000001'});assert.throws(()=>context.submitFirstContactOutcome_(owner,{workId:'WRK000001',outcome:'NO_ANSWER'}),/already exists/);assert.equal(data.Contact_Attempts.length,1)}
console.log('First Contact workflow scenarios passed');
