const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function environment(){const data={Brand_List:[{Brand_ID:'BRD000001',Brand_Name:'Alpha',Brand_Code:'ALPHA',Market:'LK',Default_Language:'EN',Status:'ACTIVE'},{Brand_ID:'BRD000002',Brand_Name:'Off',Brand_Code:'OFF',Status:'INACTIVE'}],Staff_List:[{Staff_ID:'STF000001',Display_Name:'Agent',Status:'ACTIVE',Team:'TEM000001'},{Staff_ID:'STF000002',Display_Name:'Off',Status:'INACTIVE',Team:'TEM000001'}],Team_List:[{Team_ID:'TEM000001',Team_Code:'SALES',Status:'ACTIVE'}],Affiliates:[],Affiliate_Pool:[],Assignments:[],Work_Items:[],Import_Batches:[]},counters={};const context={console,Date,Array,isFinite,Math,String,Number,JSON,Error,requireRole_:(u,roles)=>{if(!roles.includes(u.Role))throw context.apiError_('FORBIDDEN','Denied')},apiError_:(code,message)=>Object.assign(new Error(message),{code}),rows_:name=>data[name],clearCache_:()=>{},now_:()=>new Date().toISOString(),config_:()=>24,LockService:{getScriptLock:()=>({waitLock:()=>{},releaseLock:()=>{}})},reserveIdsUnlocked_:(entity,count)=>Array.from({length:count},()=>{counters[entity]=(counters[entity]||0)+1;return ({Import:'IMP',Affiliate:'AFF',Assignment:'ASN',Work:'WRK'}[entity])+String(counters[entity]).padStart(6,'0')}),appendRows_:(name,rows)=>data[name].push(...rows.map(x=>({...x}))),updateById_:(name,column,id,changes)=>{const row=data[name].find(x=>x[column]===id);if(!row)return null;const before={...row};Object.assign(row,changes);return before},audit_:()=>{}};vm.createContext(context);vm.runInContext(fs.readFileSync('backend/Import.gs','utf8'),context);return {context,data}}
const admin={Staff_ID:'STFADMIN',Role:'ADMIN'},base={brandId:'BRD000001',destination:'STAFF',staffId:'STF000001',mode:'NEW_PROSPECTS'};const row=(username,email='',phone='')=>({username,fullName:username,email,phone});
{
  const {context,data}=environment(),rows=[row('one','one@example.com'),row('two','','+94770000001'),row('three','three@example.com')];const valid=context.validateImport_(admin,{...base,rows});assert.equal(valid.summary.validRows,3);const result=context.importAffiliates_(admin,{...base,rows});assert.deepEqual([result.importedAffiliates,result.assignmentsCreated,result.workItemsCreated],[3,3,3]);assert.equal(data.Work_Items[0].Status,'PENDING');assert.equal(data.Import_Batches.length,1);
  const repeated=context.validateImport_(admin,{...base,rows});assert.equal(repeated.summary.existingAffiliates,3);assert.equal(repeated.summary.validRows,0);
}
{
  const {context,data}=environment(),rows=[row('pool1','p1@example.com'),row('pool2','','+94770000002'),row('pool3','p3@example.com')];const result=context.importAffiliates_(admin,{...base,destination:'POOL',staffId:'',rows});assert.equal(result.poolRowsAdded,3);assert.equal(data.Affiliates.length,0);assert.equal(data.Assignments.length,0);assert.ok(data.Affiliate_Pool.every(x=>x.Brand==='ALPHA'));assert.equal(context.validateImport_(admin,{...base,destination:'POOL',staffId:'',rows:[row('pool1','new@example.com')]}).summary.validRows,0);
}
{
  const {context,data}=environment();data.Affiliates.push({Affiliate_ID:'AFF999999',Affiliate_Username:'existing',Email:'used@example.com',Phone:'+94771111111',Archive_Status:'ACTIVE'},{Affiliate_ID:'AFF999998',Affiliate_Username:'closed',Email:'closed@example.com',Phone:'',Archive_Status:'ARCHIVED'});data.Assignments.push({Affiliate_ID:'AFF999999',Status:'ACTIVE'});let v=context.validateImport_(admin,{...base,rows:[row('dup','same@example.com'),row('DUP','same@example.com'),row('email-conflict','used@example.com'),row('phone-conflict','', '+94771111111'),row('missing'),row('existing','x@example.com'),row('closed','closed@example.com')]});assert.equal(v.summary.validRows,0);assert.equal(v.summary.duplicateUsernames,2);assert.equal(v.summary.duplicateEmails,2);assert.equal(v.summary.missingContact,1);assert.equal(v.summary.existingActiveAssignment,1);assert.equal(v.summary.archivedMatches,1);
  assert.throws(()=>context.validateImport_(admin,{...base,brandId:'BRD000002',rows:[row('x','x@example.com')]}),/active brand/);assert.throws(()=>context.validateImport_(admin,{...base,staffId:'STF000002',rows:[row('x','x@example.com')]}),/active staff/);assert.throws(()=>context.validateImport_({Role:'STAFF'},{...base,rows:[row('x','x@example.com')]}),e=>e.code==='FORBIDDEN');
}
{
  const {context}=environment(),payload={...base,rows:[row('race','race@example.com')]};const first=context.importAffiliates_(admin,payload);assert.equal(first.importedAffiliates,1);assert.throws(()=>context.importAffiliates_(admin,payload),/No valid rows/);
}
console.log('Import engine scenarios passed');
