const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const owner='STF000004',other='STF000005',now=Date.now(),data={Assignments:[],Affiliates:[],Brand_List:[{Brand_ID:'BRD000001',Brand_Name:'Alpha Brand',Brand_Code:'ALPHA'}],Work_Items:[]};
for(let i=1;i<=19;i++){const n=String(i).padStart(6,'0'),affiliateId='AFF'+n,assignmentId='ASN'+n;data.Affiliates.push({Affiliate_ID:affiliateId,Affiliate_Username:'prospect'+i,Affiliate_Name:i===2?'':'Prospect '+i,Email:i===3?'':'p'+i+'@example.com',Phone:i===4?'':'+9477000'+i,Brand_ID:'BRD000001',Lifecycle_Status:'ASSIGNED',Prospect_Status:'NEW',Telegram_Status:'NOT_CONNECTED'});data.Assignments.push({Assignment_ID:assignmentId,Affiliate_ID:affiliateId,Staff_ID:owner,Brand_ID:'BRD000001',Status:'ACTIVE'});data.Work_Items.push({Work_ID:'WRK'+n,Affiliate_ID:affiliateId,Assignment_ID:assignmentId,Staff_ID:owner,Work_Type:'FIRST_CONTACT',Work_Channel:'CALL',Priority:i===2?'HIGH':'NORMAL',Status:'PENDING',Title:'Initial affiliate contact',Reason:'NEW_PROSPECT',Assigned_At:new Date(now-i*60000).toISOString(),Due_At:new Date(now+(i===1?-3600000:i*3600000)).toISOString(),Started_At:''})}
data.Work_Items.push({...data.Work_Items[0],Work_ID:'WRK900001',Status:'COMPLETED'},{...data.Work_Items[0],Work_ID:'WRK900002',Staff_ID:other},{...data.Work_Items[0],Work_ID:'WRK900003',Affiliate_ID:'ORPHAN',Assignment_ID:'MISSING'},{...data.Work_Items[0],Work_ID:'WRK900004',Affiliate_ID:'MISSING',Assignment_ID:'MISSING'});
const context={console,Date,String,Number,Math,isFinite,rows_:name=>data[name],page_:(items,p)=>({items:items.slice(0,p.pageSize||100),page:p.page||1,pageSize:p.pageSize||100,total:items.length})};vm.createContext(context);vm.runInContext(fs.readFileSync('backend/Services.gs','utf8'),context);
const result=context.myWork_({Staff_ID:owner,Role:'STAFF'},{staffId:other,page:1,pageSize:100});assert.equal(result.total,19);assert.ok(result.items.every(x=>x.assignmentId&&x.affiliateId&&x.brandId==='BRD000001'));assert.equal(result.items[0].overdue,true);assert.equal(result.items[0].workId,'WRK000001');assert.equal(result.items[1].priority,'HIGH');assert.equal(result.items[1].brandName,'Alpha Brand');assert.equal(result.items[1].brandCode,'ALPHA');assert.equal(result.items.find(x=>x.affiliateId==='AFF000002').affiliateName,'');assert.equal(context.myWork_({Staff_ID:other,Role:'STAFF'},{staffId:owner,page:1,pageSize:100}).total,0);assert.ok(!JSON.stringify(result).match(/Password_Hash|Session_Token_Hash|token/i));
for(const query of ['prospect17','Prospect 17','p17@example.com','+947700017','alpha brand']){const found=context.myWork_({Staff_ID:owner,Role:'STAFF'},{search:`  ${query.toUpperCase()}  `,pageSize:100});assert.ok(found.items.length>0,`search must match ${query}`);assert.equal(found.summary.open,19)}
const pagedSearch=context.myWork_({Staff_ID:owner,Role:'STAFF'},{search:'prospect17',pageSize:1});assert.equal(pagedSearch.total,1);assert.equal(pagedSearch.items[0].affiliateUsername,'prospect17');assert.equal(context.myWork_({Staff_ID:owner,Role:'STAFF'},{search:'   ',pageSize:100}).total,19);assert.equal(context.myWork_({Staff_ID:other,Role:'STAFF'},{search:'prospect17',pageSize:100}).total,0);assert.equal(context.myWork_({Staff_ID:owner,Role:'STAFF'},{search:'prospect',pageSize:100}).items[0].workId,result.items[0].workId);
const ui=fs.readFileSync('app/my-work/page.tsx','utf8'),workspace=fs.readFileSync('app/affiliates/page.tsx','utf8');assert.match(ui,/api\.getMyWork\(page,50,\{filter,search\}\)/);assert.match(ui,/setPage\(1\);setSearch/);assert.match(ui,/setTimeout\(\(\)=>void load\(\),search\?250:0\)/);assert.match(workspace,/submitFirstContactOutcome\(payload\)/);assert.match(workspace,/Contact workflow/);assert.match(workspace,/Record Contact Outcome/);assert.match(workspace,/Record Outcome/);assert.ok(!workspace.includes('Save Outcome'));
console.log('My Work service scenarios passed');
