export type AffiliateLifecycle =
  | 'UNASSIGNED'
  | 'ASSIGNED'
  | 'CONTACT_PENDING'
  | 'CONTACTING'
  | 'CONNECTED'
  | 'CALLBACK'
  | 'RETRY'
  | 'TELEGRAM_ONBOARDING'
  | 'TELEGRAM_CONNECTED'
  | 'MANAGED'
  | 'AT_RISK'
  | 'DORMANT'
  | 'REACTIVATION'
  | 'CONTACT_EXHAUSTED'
  | 'ARCHIVED'
  | 'REPLACEMENT_REQUIRED';

export type WorkStatus = 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'SKIPPED' | 'CANCELLED' | 'OVERDUE';
export type StaffRole = 'STAFF' | 'SUPERVISOR' | 'ADMIN' | 'SUPER_ADMIN';

export type ContactOutcome =
  | 'CONNECTED'
  | 'NO_ANSWER'
  | 'BUSY'
  | 'UNREACHABLE'
  | 'WRONG_PERSON'
  | 'INVALID_NUMBER'
  | 'CALLBACK_REQUESTED'
  | 'NOT_INTERESTED'
  | 'STOPPED_WORKING'
  | 'TELEGRAM_CONNECTED';
