'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {api,ApiError,FollowupItem,FollowupsResponse} from '../../lib/api-client';
import {EMAIL_TOOL_URL} from '../../lib/external-tools';
import {clearReadCache,readCache,writeCache} from '../../lib/read-cache';
import styles from './follow-ups.module.css';

export default function FollowupsPage(){const [initial]=useState(()=>readCache<FollowupsResponse>('followups')),[data,setData]=useState<FollowupsResponse|null>(initial),[loading,setLoading]=useState(!initial),[error,setError]=useState('');const load=useCallback(async()=>{setError('');try{const response=await api.getMyFollowups();setData(response);writeCache('followups',response)}catch(cause){const auth=cause instanceof ApiError&&['UNAUTHENTICATED','SESSION_EXPIRED','FORBIDDEN'].includes(cause.code);if(!initial||auth){if(auth){clearReadCache();setData(null)}setError(cause instanceof ApiError?cause.message:'Your follow-ups could not be loaded.')}}finally{setLoading(false)}},[initial]);useEffect(()=>{void load()},[load]);return <><div className="section-head"><div><h1>Follow-ups</h1><p className="muted">Scheduled callbacks and commitments, ordered by urgency.</p></div>{!loading&&<button className={styles.refresh} onClick={()=>void load()}>Refresh</button>}</div>{data&&<div className={styles.summary}>{[['Open Follow-ups',data.summary.open],['Overdue',data.summary.overdue],['Due Today',data.summary.dueToday],['Upcoming',data.summary.upcoming]].map(([label,value])=><section className="card" key={label}><span>{label}</span><b>{value}</b></section>)}</div>}{loading?<State title="Loading follow-ups…" detail="Retrieving your current assigned follow-ups."/>:error?<State title="Unable to load Follow-ups" detail={error} action={<button className="primary" onClick={()=>void load()}>Retry</button>}/>:!data?.items.length?<State title="No follow-ups yet" detail="No follow-up history is available in your assignment scope."/>:<FollowupList items={data.items}/>}</>}
function FollowupList({items}:{items:FollowupItem[]}){return <section className="card"><div className="section-head"><div><h2>Follow-up schedule</h2><p className="muted">{items.length} record{items.length===1?'':'s'}</p></div></div><div className={styles.tableWrap}><table className="table"><thead><tr><th>Affiliate</th><th>Brand</th><th>Follow-up</th><th>Channel</th><th>Due</th><th>Status</th><th>Contact</th><th>Action</th></tr></thead><tbody>{items.map(item=><tr className={item.overdue?styles.overdueRow:''} key={item.followupId}><td><strong>{item.affiliateUsername}</strong><small>{item.affiliateName||'Name not provided'}</small><Copy label="Username" value={item.affiliateUsername}/></td><td>{item.brandName||item.brandCode||'—'}</td><td>{label_(item.followupType)}<small>{item.notes||item.followupId}</small></td><td>{label_(item.channel)}</td><td>{date_(item.dueAt)}</td><td><Badge item={item}/></td><td><Copy label="Email" value={item.email}/><Copy label="Phone" value={item.phone}/></td><td><Actions item={item}/></td></tr>)}</tbody></table></div><div className={styles.mobileList}>{items.map(item=><article className={styles.mobileCard} key={item.followupId}><div><strong>{item.affiliateUsername}</strong><span>{item.affiliateName||'Name not provided'}</span></div><div className={styles.badges}><Badge item={item}/><span>{label_(item.priority)}</span></div><p>{item.brandName||item.brandCode||'No brand'} · {label_(item.followupType)} · {date_(item.dueAt)}</p><Copy label="Username" value={item.affiliateUsername}/><Copy label="Email" value={item.email}/><Copy label="Phone" value={item.phone}/><Actions item={item}/></article>)}</div></section>}
function Actions({item}:{item:FollowupItem}){const href=item.linkedWorkId?`/affiliates?workId=${encodeURIComponent(item.linkedWorkId)}`:`/affiliates?affiliateId=${encodeURIComponent(item.affiliateId)}`;return <div className={styles.actions}><Link className={styles.open} href={href}>{item.linkedWorkId?'Open Callback':'Open Affiliate'}</Link>{item.email&&<a className={styles.email} href={EMAIL_TOOL_URL} target="_blank" rel="noopener noreferrer">Send Email</a>}</div>}
function Copy({label,value}:{label:string;value:string}){const [copied,setCopied]=useState(false);if(!value)return <small>{label}: —</small>;async function copy(){try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(value);else{const area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove()}setCopied(true);window.setTimeout(()=>setCopied(false),1400)}catch{setCopied(false)}}return <span className={styles.copy}><span>{value}</span><button type="button" onClick={()=>void copy()} aria-label={`Copy ${label}`}>{copied?'Copied':'Copy'}</button></span>}
function Badge({item}:{item:FollowupItem}){const value=item.overdue?'OVERDUE':item.dueToday?'DUE_TODAY':item.status;return <span className={`${styles.badge} ${item.overdue?styles.urgent:''}`}>{label_(value)}</span>}
function State({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}){return <section className="card empty-state"><div><div className="empty-icon">↗</div><h2>{title}</h2><p className="muted">{detail}</p>{action}</div></section>}
function label_(value:string){return String(value||'—').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function date_(value:string){if(!value)return'No due date';const date=new Date(value);return Number.isNaN(date.getTime())?'Invalid date':new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(date)}
