'use client';
import { useEffect, useMemo, useState } from 'react';
import { api, ApiError, BrandRecord, CurrentUser, ImportCommitResult, ImportInputRow, ImportValidation, StaffRecord } from '../../../lib/api-client';
import styles from './import.module.css';

function parseLine(line:string,delimiter:string){const cells:string[]=[];let cell='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===delimiter&&!quoted){cells.push(cell.trim());cell=''}else cell+=c}cells.push(cell.trim());return cells}
function parsePaste(text:string):ImportInputRow[]{const lines=text.replace(/\r/g,'').split('\n').filter(line=>line.trim());if(!lines.length)return [];const delimiter=lines.some(line=>line.includes('\t'))?'\t':',';let rows=lines.map(line=>parseLine(line,delimiter));if(/affiliate[ _-]*username/i.test(rows[0]?.[0]||''))rows=rows.slice(1);return rows.map(c=>({username:c[0]||'',fullName:c[1]||'',email:c[2]||'',phone:c[3]||''}))}

export default function ImportPage(){
  const [authorized,setAuthorized]=useState<boolean|null>(null),[brands,setBrands]=useState<BrandRecord[]>([]),[staff,setStaff]=useState<StaffRecord[]>([]),[brandId,setBrandId]=useState(''),[destination,setDestination]=useState<'STAFF'|'POOL'>('STAFF'),[staffId,setStaffId]=useState(''),[text,setText]=useState(''),[validation,setValidation]=useState<ImportValidation|null>(null),[committed,setCommitted]=useState<ImportCommitResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let user:CurrentUser|null=null;try{const saved=localStorage.getItem('crm_user');user=saved?JSON.parse(saved) as CurrentUser:null}catch{}const allowed=user?.role==='ADMIN'||user?.role==='SUPER_ADMIN';setAuthorized(allowed);if(!allowed)return;Promise.all([api.listBrands(),api.listStaff()]).then(([b,s])=>{const activeBrands=b.filter(x=>x.status==='ACTIVE'),activeStaff=s.filter(x=>x.status==='ACTIVE'&&x.role!=='SUPER_ADMIN');setBrands(activeBrands);setStaff(activeStaff);setBrandId(activeBrands[0]?.brandId||'');setStaffId(activeStaff[0]?.staffId||'')}).catch(e=>setError(e instanceof Error?e.message:'Unable to load import configuration.'))},[]);
  const parsed=useMemo(()=>parsePaste(text),[text]);
  function payload(){return {brandId,destination,staffId:destination==='STAFF'?staffId:'',mode:'NEW_PROSPECTS',rows:parsed}}
  async function validate(){setBusy(true);setError('');setCommitted(null);try{setValidation(await api.validateAffiliateImport(payload()))}catch(e){setValidation(null);setError(e instanceof ApiError?e.message:'Validation failed.')}finally{setBusy(false)}}
  async function commit(){if(!validation)return;setBusy(true);setError('');try{const result=await api.commitAffiliateImport(payload());setCommitted(result);setValidation(null);setText('')}catch(e){setError(e instanceof ApiError?e.message:'Commit failed. Please validate again.')}finally{setBusy(false)}}
  function clear(){setText('');setValidation(null);setCommitted(null);setError('')}
  function changed(){setValidation(null);setCommitted(null)}
  if(authorized===null)return <section className="card empty-state"><div><h2>Checking access…</h2></div></section>;if(!authorized)return <section className="card empty-state"><div><h2>Access denied</h2><p className="muted">Bulk import is available only to ADMIN and SUPER_ADMIN.</p></div></section>;
  return <>
    <div className="section-head"><div><h1>Bulk Affiliate Import &amp; Assignment</h1><p className="muted">Validate pasted prospect data before anything is written.</p></div><span className={styles.limit}>Maximum 500 rows</span></div>
    {error&&<div className={styles.error}>{error}</div>}{committed&&<section className={`${styles.result} card`}><h2>Import committed</h2><div className={styles.resultGrid}><b>{committed.importedAffiliates}<small>Affiliates</small></b><b>{committed.assignmentsCreated}<small>Assignments</small></b><b>{committed.poolRowsAdded}<small>Pool rows</small></b><b>{committed.skippedRows}<small>Skipped</small></b></div><p>Import Batch ID: <code>{committed.importBatchId}</code></p></section>}
    <section className={`card ${styles.configuration}`}><h2>Configuration</h2><div className={styles.fields}><label>Brand<select value={brandId} onChange={e=>{setBrandId(e.target.value);changed()}}><option value="">Select active brand</option>{brands.map(b=><option key={b.brandId} value={b.brandId}>{b.brandName} ({b.brandCode})</option>)}</select></label><label>Destination<select value={destination} onChange={e=>{setDestination(e.target.value as 'STAFF'|'POOL');changed()}}><option value="STAFF">Assign directly to staff</option><option value="POOL">Affiliate Pool</option></select></label>{destination==='STAFF'&&<label>Active staff<select value={staffId} onChange={e=>{setStaffId(e.target.value);changed()}}><option value="">Select staff member</option>{staff.map(s=><option key={s.staffId} value={s.staffId}>{s.displayName} · {s.username}</option>)}</select></label>}<label>Import mode<select value="NEW_PROSPECTS" disabled><option>NEW_PROSPECTS</option></select><small>Update contacts and reopen closed are coming later.</small></label></div></section>
    <section className={`card ${styles.inputCard}`}><div className="section-head"><div><h2>Paste prospect data</h2><p className="muted">TSV or CSV: Affiliate Username, Full Name, Email, Phone Number. A header row is optional.</p></div><span className={styles.rowCount}>{parsed.length} rows detected</span></div><textarea value={text} onChange={e=>{setText(e.target.value);changed()}} placeholder={'Affiliate_Username\tFull_Name\tEmail\tPhone_Number\nprospect_01\tJane Doe\tjane@example.com\t+94770000000'} spellCheck={false}/><div className={styles.actions}><button onClick={clear} disabled={busy}>Clear</button><button className="primary" onClick={validate} disabled={busy||!brandId||!parsed.length||(destination==='STAFF'&&!staffId)}>{busy?'Working…':'Validate'}</button></div></section>
    {validation&&<><div className={styles.summary}>{[['Total',validation.summary.totalRows],['Valid',validation.summary.validRows],['Invalid',validation.summary.invalidRows],['Existing',validation.summary.existingAffiliates],['Duplicates',validation.summary.duplicateRows]].map(([label,value])=><div className="card" key={label}><span>{label}</span><b>{value}</b></div>)}</div><div className={styles.diagnostics}>Duplicate usernames: {validation.summary.duplicateUsernames} · emails: {validation.summary.duplicateEmails} · phones: {validation.summary.duplicatePhones} · missing contact: {validation.summary.missingContact} · invalid contact format: {validation.summary.invalidContactFormat} · active assignments: {validation.summary.existingActiveAssignment} · archived matches: {validation.summary.archivedMatches}</div><section className="card"><div className="section-head"><div><h2>Validation preview</h2><p className="muted">Only rows marked valid will be committed. Invalid rows remain skipped.</p></div><button className="primary" onClick={commit} disabled={busy||!validation.summary.validRows}>{busy?'Committing…':'Commit Valid Rows'}</button></div><div className={styles.tableWrap}><table className="table"><thead><tr><th>Row</th><th>Username</th><th>Name</th><th>Email</th><th>Phone</th><th>Status</th><th>Reason</th></tr></thead><tbody>{validation.rows.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.username||'—'}</td><td>{r.fullName||'—'}</td><td>{r.email||'—'}</td><td>{r.phone||'—'}</td><td><span className={`${styles.status} ${r.status==='VALID'?styles.valid:styles.invalid}`}>{r.status}</span></td><td>{r.reasons.join(' ')||'Ready to import'}</td></tr>)}</tbody></table></div></section></>}
  </>
}
