'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {api,ApiError,InteractionItem,InteractionsResponse} from '../../lib/api-client';
import {clearReadCache,readCache,writeCache} from '../../lib/read-cache';
import {filterInteractions,InteractionFilter,toggleFilter} from '../../lib/operational-filters';
import styles from './interactions.module.css';

export default function InteractionsPage(){const [initial]=useState(()=>readCache<InteractionsResponse>('interactions')),[data,setData]=useState<InteractionsResponse|null>(initial),[loading,setLoading]=useState(!initial),[error,setError]=useState(''),[filter,setFilter]=useState<InteractionFilter>('all'),[search,setSearch]=useState('');const load=useCallback(async()=>{setError('');try{const response=await api.getMyInteractions();setData(response);writeCache('interactions',response)}catch(cause){const auth=cause instanceof ApiError&&['UNAUTHENTICATED','SESSION_EXPIRED','FORBIDDEN'].includes(cause.code);if(!initial||auth){if(auth){clearReadCache();setData(null)}setError(cause instanceof ApiError?cause.message:'Interaction history could not be loaded.')}}finally{setLoading(false)}},[initial]);useEffect(()=>{void load()},[load]);const items=data?.items||[],summary=useMemo(()=>({all:items.length,today:filterInteractions(items,'today','').length,calls:filterInteractions(items,'calls','').length,followup:filterInteractions(items,'followup','').length}),[items]),filtered=useMemo(()=>filterInteractions(items,filter,search),[items,filter,search]),cards:Array<[string,number,InteractionFilter]>=[['Total Interactions',summary.all,'all'],['Today',summary.today,'today'],['Calls',summary.calls,'calls'],['Follow-up Needed',summary.followup,'followup']];return <><div className="section-head"><div><h1>Interactions</h1><p className="muted">Permanent contact history for affiliates in your current assignment scope.</p></div>{!loading&&<button className={styles.refresh} onClick={()=>void load()}>Refresh</button>}</div>{data&&<><div className={styles.summary}>{cards.map(([label,value,key])=><button type="button" aria-pressed={filter===key} className={`card ${styles.summaryButton} ${filter===key?styles.summaryActive:''}`} key={key} onClick={()=>setFilter(current=>toggleFilter(current,key,'all'))}><span>{label}</span><b>{value}</b></button>)}</div><div className={styles.search}><input aria-label="Search interactions" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search affiliate, brand, type, channel, outcome or staff"/><p>Showing {filtered.length} of {items.length} loaded interactions{data.total>items.length?` (${data.total} total)`:''}</p></div></>}{loading?<State title="Loading interactions…" detail="Retrieving authorized contact history."/>:error?<State title="Unable to load Interactions" detail={error} action={<button className="primary" onClick={()=>void load()}>Retry</button>}/>:!items.length?<State title="No interactions yet" detail="No interaction or contact-attempt history is available in your assignment scope."/>:!filtered.length?<State title="No matching interactions" detail="No loaded interactions match this filter and search."/>:<InteractionList items={filtered}/>}</>}
function InteractionList({items}:{items:InteractionItem[]}){return <section className="card"><div className="section-head"><div><h2>Interaction history</h2><p className="muted">{items.length} result{items.length===1?'':'s'} · newest first</p></div></div><div className={styles.tableWrap}><table className="table"><thead><tr><th>Date</th><th>Affiliate</th><th>Brand</th><th>Type</th><th>Channel</th><th>Outcome</th><th>Staff</th><th>Notes</th><th>Action</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{date_(item.timestamp)}</td><td><strong>{item.affiliateUsername}</strong><small>{item.affiliateName||'Name not provided'}</small><Copy value={item.affiliateUsername}/></td><td>{item.brandName||item.brandCode||'—'}</td><td><Badge value={item.type}/></td><td>{label_(item.channel)}</td><td>{label_(item.outcome)}</td><td>{item.staffName||'—'}</td><td className={styles.notes}>{item.notes||item.summary||'—'}</td><td><Link className={styles.open} href={`/affiliates?affiliateId=${encodeURIComponent(item.affiliateId)}`}>View Affiliate</Link></td></tr>)}</tbody></table></div><div className={styles.mobileList}>{items.map(item=><article className={styles.mobileCard} key={item.id}><div><strong>{item.affiliateUsername}</strong><span>{item.affiliateName||'Name not provided'}</span></div><div className={styles.badges}><Badge value={item.type}/><span>{label_(item.channel)}</span></div><p>{date_(item.timestamp)} · {item.brandName||item.brandCode||'No brand'}</p><p>{label_(item.outcome)} · {item.staffName||'Unknown staff'}</p>{(item.notes||item.summary)&&<p className={styles.notes}>{item.notes||item.summary}</p>}<Copy value={item.affiliateUsername}/><Link className={styles.open} href={`/affiliates?affiliateId=${encodeURIComponent(item.affiliateId)}`}>View Affiliate</Link></article>)}</div></section>}
function Copy({value}:{value:string}){const [copied,setCopied]=useState(false);async function copy(){try{await navigator.clipboard.writeText(value);setCopied(true);window.setTimeout(()=>setCopied(false),1400)}catch{setCopied(false)}}return <button type="button" className={styles.copy} onClick={()=>void copy()}>{copied?'Copied':'Copy Username'}</button>}
function Badge({value}:{value:string}){return <span className={styles.badge}>{label_(value)}</span>}
function State({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}){return <section className="card empty-state"><div><div className="empty-icon">◌</div><h2>{title}</h2><p className="muted">{detail}</p>{action}</div></section>}
function label_(value:string){return String(value||'—').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function date_(value:string){if(!value)return'Unknown date';const date=new Date(value);return Number.isNaN(date.getTime())?'Invalid date':new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(date)}
