const OPEN_STATUSES=['PENDING','IN_PROGRESS','OVERDUE'];
function validDate(value){const date=value?new Date(value):null;return date&&!Number.isNaN(date.getTime())?date:null}
function sameLocalDay(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function afterToday(date,now){const tomorrow=new Date(now);tomorrow.setHours(0,0,0,0);tomorrow.setDate(tomorrow.getDate()+1);return date>=tomorrow}
function filterMyWork(items,filter,now=new Date()){return items.filter(item=>{if(filter==='open')return true;if(filter==='high')return String(item.priority).toUpperCase()==='HIGH';const due=validDate(item.dueAt);if(!due)return false;if(filter==='overdue')return due.getTime()<now.getTime();if(filter==='today')return sameLocalDay(due,now);return true})}
function filterFollowups(items,filter,now=new Date()){return items.filter(item=>{if(!OPEN_STATUSES.includes(String(item.status)))return false;if(filter==='open')return true;const due=validDate(item.dueAt);if(!due)return false;if(filter==='overdue')return due.getTime()<now.getTime();if(filter==='today')return sameLocalDay(due,now);if(filter==='upcoming')return afterToday(due,now);return true})}
function filterInteractions(items,filter,search,now=new Date()){const query=String(search||'').trim().toLowerCase();return items.filter(item=>filter==='all'||filter==='today'&&validDate(item.timestamp)&&sameLocalDay(validDate(item.timestamp),now)||filter==='calls'&&String(item.channel).toUpperCase()==='CALL'||filter==='followup'&&item.followupRequired).filter(item=>!query||[item.affiliateUsername,item.affiliateName,item.brandName,item.brandCode,item.type,item.channel,item.outcome,item.staffName].some(value=>String(value||'').toLowerCase().includes(query)))}
function toggleFilter(current,next,defaultFilter){return current===next&&next!==defaultFilter?defaultFilter:next}
module.exports={filterMyWork,filterFollowups,filterInteractions,toggleFilter};
