'use client';
import Link from 'next/link';
import { FormEvent, Suspense, useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { api, ApiError, FirstContactResult, WorkWorkspace } from '../../lib/api-client';
import styles from './workspace.module.css';

export default function AffiliatesPage(){return <Suspense fallback={<WorkspaceState title="Loading workspace…" detail="Preparing the selected work item."/>}><AffiliateWorkspace/></Suspense>}
function AffiliateWorkspace(){
  const workId=useSearchParams().get('workId')||'',[workspace,setWorkspace]=useState<WorkWorkspace|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState<FirstContactResult|null>(null),[outcome,setOutcome]=useState('CONNECTED'),[telegramStatus,setTelegramStatus]=useState('TELEGRAM_NOT_CONNECTED');
  const load=useCallback(async()=>{if(!workId){setError('No work item was selected.');setLoading(false);return}setLoading(true);setError('');try{setWorkspace(await api.getWorkWorkspace(workId))}catch(cause){setWorkspace(null);setError(message_(cause))}finally{setLoading(false)}},[workId]);useEffect(()=>{void load()},[load]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy||success)return;const data=new FormData(event.currentTarget),callbackLocal=String(data.get('callbackAt')||''),payload={workId,outcome,telegramStatus:outcome==='CONNECTED'?telegramStatus:'',telegramUsername:String(data.get('telegramUsername')||''),callbackAt:callbackLocal?new Date(callbackLocal).toISOString():'',notes:String(data.get('notes')||'')};setBusy(true);setError('');try{setSuccess(await api.submitFirstContactOutcome(payload));setWorkspace(null)}catch(cause){setError(message_(cause))}finally{setBusy(false)}}
  if(loading)return <WorkspaceState title="Loading workspace…" detail="Retrieving the current affiliate and assignment."/>;if(error&&!workspace)return <WorkspaceState title="Workspace unavailable" detail={error} action={<><button className="primary" onClick={()=>void load()}>Retry</button> <Link href="/my-work">Back to My Work</Link></>}/>;if(success)return <WorkspaceState title="Outcome saved" detail={`The ${label_(success.outcome)} outcome was recorded. Contact history is preserved${success.nextWorkId?' and the next action was scheduled':''}.`} action={<Link className="primary" href="/my-work">Back to My Work</Link>}/>;if(!workspace)return null;
  const active=['PENDING','IN_PROGRESS','OVERDUE'].includes(workspace.work.status),firstContact=workspace.work.workType==='FIRST_CONTACT';return <><div className={styles.top}><Link href="/my-work">← Back to My Work</Link><span>{workspace.work.workId}</span></div><header className={styles.identity}><div><span className={styles.eyebrow}>Affiliate workspace</span><h1>{workspace.affiliate.affiliateUsername}</h1><p>{workspace.affiliate.affiliateName||'Full name not provided'} · {workspace.brand.brandName||workspace.brand.brandCode||workspace.brand.brandId}</p></div><div className={styles.chips}>{[workspace.affiliate.lifecycleStatus,workspace.affiliate.prospectStatus,workspace.affiliate.telegramStatus,workspace.work.priority].filter(Boolean).map(value=><span key={value}>{label_(value)}</span>)}</div></header>
    {error&&<div className={styles.error}>{error}</div>}<div className={styles.columns}><section className="card"><h2>Contact information</h2><dl className={styles.details}><Detail label="Email" value={workspace.affiliate.email}/><Detail label="Phone" value={workspace.affiliate.phone}/><Detail label="Telegram" value={workspace.affiliate.telegramUsername}/><Detail label="Preferred channel" value={workspace.affiliate.preferredChannel}/></dl></section><section className="card"><h2>Current work</h2><dl className={styles.details}><Detail label="Work type" value={label_(workspace.work.workType)}/><Detail label="Channel" value={label_(workspace.work.workChannel)}/><Detail label="Status" value={label_(workspace.work.status)}/><Detail label="Assigned" value={date_(workspace.work.assignedAt)}/><Detail label="Due" value={date_(workspace.work.dueAt)}/><Detail label="Staff" value={workspace.assignment.staffName}/></dl></section></div>
    <section className={`card ${styles.outcome}`}><div><span className={styles.eyebrow}>Execution workflow</span><h2>{firstContact?'First Contact':label_(workspace.work.workType)}</h2><p className="muted">Record the real call outcome. This action permanently appends operational history.</p></div>{firstContact&&active?<form onSubmit={submit}><label>Outcome<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="CONNECTED">Connected</option><option value="NO_ANSWER">No Answer</option><option value="CALLBACK_REQUESTED">Callback Requested</option><option value="WRONG_OR_INVALID_CONTACT">Wrong or Invalid Contact</option><option value="OTHER">Other</option></select></label>{outcome==='CONNECTED'&&<><label>Telegram connection status<select value={telegramStatus} onChange={e=>setTelegramStatus(e.target.value)}><option value="TELEGRAM_NOT_CONNECTED">Not connected yet</option><option value="TELEGRAM_CONNECTED">Connected</option></select></label>{telegramStatus==='TELEGRAM_CONNECTED'&&<label>Telegram username<input name="telegramUsername" maxLength={100} defaultValue={workspace.affiliate.telegramUsername}/></label>}</>}{outcome==='CALLBACK_REQUESTED'&&<label>Callback date and time<input name="callbackAt" type="datetime-local" min={localMin_()} required/></label>}<label>Notes<textarea name="notes" maxLength={1000} required={outcome==='WRONG_OR_INVALID_CONTACT'||outcome==='OTHER'} placeholder={outcome==='WRONG_OR_INVALID_CONTACT'||outcome==='OTHER'?'Required for this outcome':'Optional context for this attempt'}/></label><button className="primary" disabled={busy}>{busy?'Saving…':'Save Outcome'}</button></form>:<div className={styles.notice}>{active?'Processing for this work type is deliberately deferred.':'This work item is already complete or no longer active.'}</div>}</section></>;
}
function Detail({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value||'Not provided'}</dd></div>}
function WorkspaceState({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}){return <section className="card empty-state"><div><div className="empty-icon">◎</div><h2>{title}</h2><p className="muted">{detail}</p>{action&&<div className={styles.stateAction}>{action}</div>}</div></section>}
function message_(cause:unknown){return cause instanceof ApiError?cause.message:'The workspace request could not be completed.'}function label_(value:string){return String(value||'—').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}function date_(value:string){if(!value)return'Not scheduled';const date=new Date(value);return Number.isNaN(date.getTime())?'Invalid date':new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(date)}function localMin_(){const date=new Date(Date.now()+60000),offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
